// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: cluster.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SnapshotPartitionKind int32

const (
	SnapshotPartitionKind_SNAPSHOT_PARTITION_KIND_UNSPECIFIED   SnapshotPartitionKind = 0
	SnapshotPartitionKind_SNAPSHOT_PARTITION_KIND_USERS         SnapshotPartitionKind = 1
	SnapshotPartitionKind_SNAPSHOT_PARTITION_KIND_MESSAGES      SnapshotPartitionKind = 2
	SnapshotPartitionKind_SNAPSHOT_PARTITION_KIND_SUBSCRIPTIONS SnapshotPartitionKind = 3
)

// Enum value maps for SnapshotPartitionKind.
var (
	SnapshotPartitionKind_name = map[int32]string{
		0: "SNAPSHOT_PARTITION_KIND_UNSPECIFIED",
		1: "SNAPSHOT_PARTITION_KIND_USERS",
		2: "SNAPSHOT_PARTITION_KIND_MESSAGES",
		3: "SNAPSHOT_PARTITION_KIND_SUBSCRIPTIONS",
	}
	SnapshotPartitionKind_value = map[string]int32{
		"SNAPSHOT_PARTITION_KIND_UNSPECIFIED":   0,
		"SNAPSHOT_PARTITION_KIND_USERS":         1,
		"SNAPSHOT_PARTITION_KIND_MESSAGES":      2,
		"SNAPSHOT_PARTITION_KIND_SUBSCRIPTIONS": 3,
	}
)

func (x SnapshotPartitionKind) Enum() *SnapshotPartitionKind {
	p := new(SnapshotPartitionKind)
	*p = x
	return p
}

func (x SnapshotPartitionKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SnapshotPartitionKind) Descriptor() protoreflect.EnumDescriptor {
	return file_cluster_proto_enumTypes[0].Descriptor()
}

func (SnapshotPartitionKind) Type() protoreflect.EnumType {
	return &file_cluster_proto_enumTypes[0]
}

func (x SnapshotPartitionKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SnapshotPartitionKind.Descriptor instead.
func (SnapshotPartitionKind) EnumDescriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{0}
}

type ClusterDeliveryMode int32

const (
	ClusterDeliveryMode_CLUSTER_DELIVERY_MODE_UNSPECIFIED ClusterDeliveryMode = 0
	ClusterDeliveryMode_CLUSTER_DELIVERY_MODE_BEST_EFFORT ClusterDeliveryMode = 1
	ClusterDeliveryMode_CLUSTER_DELIVERY_MODE_ROUTE_RETRY ClusterDeliveryMode = 2
)

// Enum value maps for ClusterDeliveryMode.
var (
	ClusterDeliveryMode_name = map[int32]string{
		0: "CLUSTER_DELIVERY_MODE_UNSPECIFIED",
		1: "CLUSTER_DELIVERY_MODE_BEST_EFFORT",
		2: "CLUSTER_DELIVERY_MODE_ROUTE_RETRY",
	}
	ClusterDeliveryMode_value = map[string]int32{
		"CLUSTER_DELIVERY_MODE_UNSPECIFIED": 0,
		"CLUSTER_DELIVERY_MODE_BEST_EFFORT": 1,
		"CLUSTER_DELIVERY_MODE_ROUTE_RETRY": 2,
	}
)

func (x ClusterDeliveryMode) Enum() *ClusterDeliveryMode {
	p := new(ClusterDeliveryMode)
	*p = x
	return p
}

func (x ClusterDeliveryMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClusterDeliveryMode) Descriptor() protoreflect.EnumDescriptor {
	return file_cluster_proto_enumTypes[1].Descriptor()
}

func (ClusterDeliveryMode) Type() protoreflect.EnumType {
	return &file_cluster_proto_enumTypes[1]
}

func (x ClusterDeliveryMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClusterDeliveryMode.Descriptor instead.
func (ClusterDeliveryMode) EnumDescriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{1}
}

type Envelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	NodeId    int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Sequence  uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SentAtHlc string                 `protobuf:"bytes,3,opt,name=sent_at_hlc,json=sentAtHlc,proto3" json:"sent_at_hlc,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Envelope_Hello
	//	*Envelope_Ack
	//	*Envelope_EventBatch
	//	*Envelope_PullEvents
	//	*Envelope_SnapshotDigest
	//	*Envelope_SnapshotChunk
	//	*Envelope_TimeSyncRequest
	//	*Envelope_TimeSyncResponse
	//	*Envelope_RoutingUpdate
	//	*Envelope_TransientPacket
	Body          isEnvelope_Body `protobuf_oneof:"body"`
	Hmac          []byte          `protobuf:"bytes,12,opt,name=hmac,proto3" json:"hmac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *Envelope) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Envelope) GetSentAtHlc() string {
	if x != nil {
		return x.SentAtHlc
	}
	return ""
}

func (x *Envelope) GetBody() isEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Envelope) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Envelope) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *Envelope) GetEventBatch() *EventBatch {
	if x != nil {
		if x, ok := x.Body.(*Envelope_EventBatch); ok {
			return x.EventBatch
		}
	}
	return nil
}

func (x *Envelope) GetPullEvents() *PullEvents {
	if x != nil {
		if x, ok := x.Body.(*Envelope_PullEvents); ok {
			return x.PullEvents
		}
	}
	return nil
}

func (x *Envelope) GetSnapshotDigest() *SnapshotDigest {
	if x != nil {
		if x, ok := x.Body.(*Envelope_SnapshotDigest); ok {
			return x.SnapshotDigest
		}
	}
	return nil
}

func (x *Envelope) GetSnapshotChunk() *SnapshotChunk {
	if x != nil {
		if x, ok := x.Body.(*Envelope_SnapshotChunk); ok {
			return x.SnapshotChunk
		}
	}
	return nil
}

func (x *Envelope) GetTimeSyncRequest() *TimeSyncRequest {
	if x != nil {
		if x, ok := x.Body.(*Envelope_TimeSyncRequest); ok {
			return x.TimeSyncRequest
		}
	}
	return nil
}

func (x *Envelope) GetTimeSyncResponse() *TimeSyncResponse {
	if x != nil {
		if x, ok := x.Body.(*Envelope_TimeSyncResponse); ok {
			return x.TimeSyncResponse
		}
	}
	return nil
}

func (x *Envelope) GetRoutingUpdate() *RoutingUpdate {
	if x != nil {
		if x, ok := x.Body.(*Envelope_RoutingUpdate); ok {
			return x.RoutingUpdate
		}
	}
	return nil
}

func (x *Envelope) GetTransientPacket() *TransientPacket {
	if x != nil {
		if x, ok := x.Body.(*Envelope_TransientPacket); ok {
			return x.TransientPacket
		}
	}
	return nil
}

func (x *Envelope) GetHmac() []byte {
	if x != nil {
		return x.Hmac
	}
	return nil
}

type isEnvelope_Body interface {
	isEnvelope_Body()
}

type Envelope_Hello struct {
	Hello *Hello `protobuf:"bytes,4,opt,name=hello,proto3,oneof"`
}

type Envelope_Ack struct {
	Ack *Ack `protobuf:"bytes,5,opt,name=ack,proto3,oneof"`
}

type Envelope_EventBatch struct {
	EventBatch *EventBatch `protobuf:"bytes,6,opt,name=event_batch,json=eventBatch,proto3,oneof"`
}

type Envelope_PullEvents struct {
	PullEvents *PullEvents `protobuf:"bytes,7,opt,name=pull_events,json=pullEvents,proto3,oneof"`
}

type Envelope_SnapshotDigest struct {
	SnapshotDigest *SnapshotDigest `protobuf:"bytes,8,opt,name=snapshot_digest,json=snapshotDigest,proto3,oneof"`
}

type Envelope_SnapshotChunk struct {
	SnapshotChunk *SnapshotChunk `protobuf:"bytes,9,opt,name=snapshot_chunk,json=snapshotChunk,proto3,oneof"`
}

type Envelope_TimeSyncRequest struct {
	TimeSyncRequest *TimeSyncRequest `protobuf:"bytes,10,opt,name=time_sync_request,json=timeSyncRequest,proto3,oneof"`
}

type Envelope_TimeSyncResponse struct {
	TimeSyncResponse *TimeSyncResponse `protobuf:"bytes,11,opt,name=time_sync_response,json=timeSyncResponse,proto3,oneof"`
}

type Envelope_RoutingUpdate struct {
	RoutingUpdate *RoutingUpdate `protobuf:"bytes,13,opt,name=routing_update,json=routingUpdate,proto3,oneof"`
}

type Envelope_TransientPacket struct {
	TransientPacket *TransientPacket `protobuf:"bytes,14,opt,name=transient_packet,json=transientPacket,proto3,oneof"`
}

func (*Envelope_Hello) isEnvelope_Body() {}

func (*Envelope_Ack) isEnvelope_Body() {}

func (*Envelope_EventBatch) isEnvelope_Body() {}

func (*Envelope_PullEvents) isEnvelope_Body() {}

func (*Envelope_SnapshotDigest) isEnvelope_Body() {}

func (*Envelope_SnapshotChunk) isEnvelope_Body() {}

func (*Envelope_TimeSyncRequest) isEnvelope_Body() {}

func (*Envelope_TimeSyncResponse) isEnvelope_Body() {}

func (*Envelope_RoutingUpdate) isEnvelope_Body() {}

func (*Envelope_TransientPacket) isEnvelope_Body() {}

type Hello struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AdvertiseAddr     string                 `protobuf:"bytes,2,opt,name=advertise_addr,json=advertiseAddr,proto3" json:"advertise_addr,omitempty"`
	ProtocolVersion   string                 `protobuf:"bytes,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	OriginProgress    []*OriginProgress      `protobuf:"bytes,4,rep,name=origin_progress,json=originProgress,proto3" json:"origin_progress,omitempty"`
	SnapshotVersion   string                 `protobuf:"bytes,5,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	MessageWindowSize uint32                 `protobuf:"varint,6,opt,name=message_window_size,json=messageWindowSize,proto3" json:"message_window_size,omitempty"`
	SupportsRouting   bool                   `protobuf:"varint,7,opt,name=supports_routing,json=supportsRouting,proto3" json:"supports_routing,omitempty"`
	ConnectionId      uint64                 `protobuf:"varint,8,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	SmoothedRttMs     uint32                 `protobuf:"varint,9,opt,name=smoothed_rtt_ms,json=smoothedRttMs,proto3" json:"smoothed_rtt_ms,omitempty"`
	JitterPenaltyMs   uint32                 `protobuf:"varint,10,opt,name=jitter_penalty_ms,json=jitterPenaltyMs,proto3" json:"jitter_penalty_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *Hello) GetAdvertiseAddr() string {
	if x != nil {
		return x.AdvertiseAddr
	}
	return ""
}

func (x *Hello) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *Hello) GetOriginProgress() []*OriginProgress {
	if x != nil {
		return x.OriginProgress
	}
	return nil
}

func (x *Hello) GetSnapshotVersion() string {
	if x != nil {
		return x.SnapshotVersion
	}
	return ""
}

func (x *Hello) GetMessageWindowSize() uint32 {
	if x != nil {
		return x.MessageWindowSize
	}
	return 0
}

func (x *Hello) GetSupportsRouting() bool {
	if x != nil {
		return x.SupportsRouting
	}
	return false
}

func (x *Hello) GetConnectionId() uint64 {
	if x != nil {
		return x.ConnectionId
	}
	return 0
}

func (x *Hello) GetSmoothedRttMs() uint32 {
	if x != nil {
		return x.SmoothedRttMs
	}
	return 0
}

func (x *Hello) GetJitterPenaltyMs() uint32 {
	if x != nil {
		return x.JitterPenaltyMs
	}
	return 0
}

type OriginProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginNodeId  int64                  `protobuf:"varint,1,opt,name=origin_node_id,json=originNodeId,proto3" json:"origin_node_id,omitempty"`
	LastEventId   uint64                 `protobuf:"varint,2,opt,name=last_event_id,json=lastEventId,proto3" json:"last_event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OriginProgress) Reset() {
	*x = OriginProgress{}
	mi := &file_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OriginProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OriginProgress) ProtoMessage() {}

func (x *OriginProgress) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OriginProgress.ProtoReflect.Descriptor instead.
func (*OriginProgress) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *OriginProgress) GetOriginNodeId() int64 {
	if x != nil {
		return x.OriginNodeId
	}
	return 0
}

func (x *OriginProgress) GetLastEventId() uint64 {
	if x != nil {
		return x.LastEventId
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	OriginNodeId  int64                  `protobuf:"varint,2,opt,name=origin_node_id,json=originNodeId,proto3" json:"origin_node_id,omitempty"`
	AckedEventId  uint64                 `protobuf:"varint,3,opt,name=acked_event_id,json=ackedEventId,proto3" json:"acked_event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *Ack) GetOriginNodeId() int64 {
	if x != nil {
		return x.OriginNodeId
	}
	return 0
}

func (x *Ack) GetAckedEventId() uint64 {
	if x != nil {
		return x.AckedEventId
	}
	return 0
}

type EventBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*ReplicatedEvent     `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	PullRequestId uint64                 `protobuf:"varint,2,opt,name=pull_request_id,json=pullRequestId,proto3" json:"pull_request_id,omitempty"`
	OriginNodeId  int64                  `protobuf:"varint,3,opt,name=origin_node_id,json=originNodeId,proto3" json:"origin_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBatch) Reset() {
	*x = EventBatch{}
	mi := &file_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBatch) ProtoMessage() {}

func (x *EventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBatch.ProtoReflect.Descriptor instead.
func (*EventBatch) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *EventBatch) GetEvents() []*ReplicatedEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EventBatch) GetPullRequestId() uint64 {
	if x != nil {
		return x.PullRequestId
	}
	return 0
}

func (x *EventBatch) GetOriginNodeId() int64 {
	if x != nil {
		return x.OriginNodeId
	}
	return 0
}

type ReplicatedEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventId         int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	AggregateType   string                 `protobuf:"bytes,2,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	AggregateNodeId int64                  `protobuf:"varint,3,opt,name=aggregate_node_id,json=aggregateNodeId,proto3" json:"aggregate_node_id,omitempty"`
	AggregateId     int64                  `protobuf:"varint,4,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	Hlc             string                 `protobuf:"bytes,5,opt,name=hlc,proto3" json:"hlc,omitempty"`
	OriginNodeId    int64                  `protobuf:"varint,6,opt,name=origin_node_id,json=originNodeId,proto3" json:"origin_node_id,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*ReplicatedEvent_UserCreated
	//	*ReplicatedEvent_UserUpdated
	//	*ReplicatedEvent_UserDeleted
	//	*ReplicatedEvent_MessageCreated
	//	*ReplicatedEvent_ChannelSubscribed
	//	*ReplicatedEvent_ChannelUnsubscribed
	Body          isReplicatedEvent_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicatedEvent) Reset() {
	*x = ReplicatedEvent{}
	mi := &file_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicatedEvent) ProtoMessage() {}

func (x *ReplicatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicatedEvent.ProtoReflect.Descriptor instead.
func (*ReplicatedEvent) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *ReplicatedEvent) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *ReplicatedEvent) GetAggregateType() string {
	if x != nil {
		return x.AggregateType
	}
	return ""
}

func (x *ReplicatedEvent) GetAggregateNodeId() int64 {
	if x != nil {
		return x.AggregateNodeId
	}
	return 0
}

func (x *ReplicatedEvent) GetAggregateId() int64 {
	if x != nil {
		return x.AggregateId
	}
	return 0
}

func (x *ReplicatedEvent) GetHlc() string {
	if x != nil {
		return x.Hlc
	}
	return ""
}

func (x *ReplicatedEvent) GetOriginNodeId() int64 {
	if x != nil {
		return x.OriginNodeId
	}
	return 0
}

func (x *ReplicatedEvent) GetBody() isReplicatedEvent_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ReplicatedEvent) GetUserCreated() *UserCreatedEvent {
	if x != nil {
		if x, ok := x.Body.(*ReplicatedEvent_UserCreated); ok {
			return x.UserCreated
		}
	}
	return nil
}

func (x *ReplicatedEvent) GetUserUpdated() *UserUpdatedEvent {
	if x != nil {
		if x, ok := x.Body.(*ReplicatedEvent_UserUpdated); ok {
			return x.UserUpdated
		}
	}
	return nil
}

func (x *ReplicatedEvent) GetUserDeleted() *UserDeletedEvent {
	if x != nil {
		if x, ok := x.Body.(*ReplicatedEvent_UserDeleted); ok {
			return x.UserDeleted
		}
	}
	return nil
}

func (x *ReplicatedEvent) GetMessageCreated() *MessageCreatedEvent {
	if x != nil {
		if x, ok := x.Body.(*ReplicatedEvent_MessageCreated); ok {
			return x.MessageCreated
		}
	}
	return nil
}

func (x *ReplicatedEvent) GetChannelSubscribed() *ChannelSubscribedEvent {
	if x != nil {
		if x, ok := x.Body.(*ReplicatedEvent_ChannelSubscribed); ok {
			return x.ChannelSubscribed
		}
	}
	return nil
}

func (x *ReplicatedEvent) GetChannelUnsubscribed() *ChannelUnsubscribedEvent {
	if x != nil {
		if x, ok := x.Body.(*ReplicatedEvent_ChannelUnsubscribed); ok {
			return x.ChannelUnsubscribed
		}
	}
	return nil
}

type isReplicatedEvent_Body interface {
	isReplicatedEvent_Body()
}

type ReplicatedEvent_UserCreated struct {
	UserCreated *UserCreatedEvent `protobuf:"bytes,7,opt,name=user_created,json=userCreated,proto3,oneof"`
}

type ReplicatedEvent_UserUpdated struct {
	UserUpdated *UserUpdatedEvent `protobuf:"bytes,8,opt,name=user_updated,json=userUpdated,proto3,oneof"`
}

type ReplicatedEvent_UserDeleted struct {
	UserDeleted *UserDeletedEvent `protobuf:"bytes,9,opt,name=user_deleted,json=userDeleted,proto3,oneof"`
}

type ReplicatedEvent_MessageCreated struct {
	MessageCreated *MessageCreatedEvent `protobuf:"bytes,10,opt,name=message_created,json=messageCreated,proto3,oneof"`
}

type ReplicatedEvent_ChannelSubscribed struct {
	ChannelSubscribed *ChannelSubscribedEvent `protobuf:"bytes,11,opt,name=channel_subscribed,json=channelSubscribed,proto3,oneof"`
}

type ReplicatedEvent_ChannelUnsubscribed struct {
	ChannelUnsubscribed *ChannelUnsubscribedEvent `protobuf:"bytes,12,opt,name=channel_unsubscribed,json=channelUnsubscribed,proto3,oneof"`
}

func (*ReplicatedEvent_UserCreated) isReplicatedEvent_Body() {}

func (*ReplicatedEvent_UserUpdated) isReplicatedEvent_Body() {}

func (*ReplicatedEvent_UserDeleted) isReplicatedEvent_Body() {}

func (*ReplicatedEvent_MessageCreated) isReplicatedEvent_Body() {}

func (*ReplicatedEvent_ChannelSubscribed) isReplicatedEvent_Body() {}

func (*ReplicatedEvent_ChannelUnsubscribed) isReplicatedEvent_Body() {}

type UserCreatedEvent struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	NodeId              int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	UserId              int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username            string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash        string                 `protobuf:"bytes,4,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Profile             string                 `protobuf:"bytes,5,opt,name=profile,proto3" json:"profile,omitempty"`
	Role                string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	SystemReserved      bool                   `protobuf:"varint,7,opt,name=system_reserved,json=systemReserved,proto3" json:"system_reserved,omitempty"`
	CreatedAtHlc        string                 `protobuf:"bytes,8,opt,name=created_at_hlc,json=createdAtHlc,proto3" json:"created_at_hlc,omitempty"`
	UpdatedAtHlc        string                 `protobuf:"bytes,9,opt,name=updated_at_hlc,json=updatedAtHlc,proto3" json:"updated_at_hlc,omitempty"`
	VersionUsername     string                 `protobuf:"bytes,10,opt,name=version_username,json=versionUsername,proto3" json:"version_username,omitempty"`
	VersionPasswordHash string                 `protobuf:"bytes,11,opt,name=version_password_hash,json=versionPasswordHash,proto3" json:"version_password_hash,omitempty"`
	VersionProfile      string                 `protobuf:"bytes,12,opt,name=version_profile,json=versionProfile,proto3" json:"version_profile,omitempty"`
	VersionRole         string                 `protobuf:"bytes,13,opt,name=version_role,json=versionRole,proto3" json:"version_role,omitempty"`
	OriginNodeId        int64                  `protobuf:"varint,14,opt,name=origin_node_id,json=originNodeId,proto3" json:"origin_node_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UserCreatedEvent) Reset() {
	*x = UserCreatedEvent{}
	mi := &file_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreatedEvent) ProtoMessage() {}

func (x *UserCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreatedEvent.ProtoReflect.Descriptor instead.
func (*UserCreatedEvent) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *UserCreatedEvent) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *UserCreatedEvent) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserCreatedEvent) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserCreatedEvent) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *UserCreatedEvent) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *UserCreatedEvent) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserCreatedEvent) GetSystemReserved() bool {
	if x != nil {
		return x.SystemReserved
	}
	return false
}

func (x *UserCreatedEvent) GetCreatedAtHlc() string {
	if x != nil {
		return x.CreatedAtHlc
	}
	return ""
}

func (x *UserCreatedEvent) GetUpdatedAtHlc() string {
	if x != nil {
		return x.UpdatedAtHlc
	}
	return ""
}

func (x *UserCreatedEvent) GetVersionUsername() string {
	if x != nil {
		return x.VersionUsername
	}
	return ""
}

func (x *UserCreatedEvent) GetVersionPasswordHash() string {
	if x != nil {
		return x.VersionPasswordHash
	}
	return ""
}

func (x *UserCreatedEvent) GetVersionProfile() string {
	if x != nil {
		return x.VersionProfile
	}
	return ""
}

func (x *UserCreatedEvent) GetVersionRole() string {
	if x != nil {
		return x.VersionRole
	}
	return ""
}

func (x *UserCreatedEvent) GetOriginNodeId() int64 {
	if x != nil {
		return x.OriginNodeId
	}
	return 0
}

type UserUpdatedEvent struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	NodeId              int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	UserId              int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username            string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash        string                 `protobuf:"bytes,4,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Profile             string                 `protobuf:"bytes,5,opt,name=profile,proto3" json:"profile,omitempty"`
	Role                string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	SystemReserved      bool                   `protobuf:"varint,7,opt,name=system_reserved,json=systemReserved,proto3" json:"system_reserved,omitempty"`
	CreatedAtHlc        string                 `protobuf:"bytes,8,opt,name=created_at_hlc,json=createdAtHlc,proto3" json:"created_at_hlc,omitempty"`
	UpdatedAtHlc        string                 `protobuf:"bytes,9,opt,name=updated_at_hlc,json=updatedAtHlc,proto3" json:"updated_at_hlc,omitempty"`
	DeletedAtHlc        string                 `protobuf:"bytes,10,opt,name=deleted_at_hlc,json=deletedAtHlc,proto3" json:"deleted_at_hlc,omitempty"`
	VersionUsername     string                 `protobuf:"bytes,11,opt,name=version_username,json=versionUsername,proto3" json:"version_username,omitempty"`
	VersionPasswordHash string                 `protobuf:"bytes,12,opt,name=version_password_hash,json=versionPasswordHash,proto3" json:"version_password_hash,omitempty"`
	VersionProfile      string                 `protobuf:"bytes,13,opt,name=version_profile,json=versionProfile,proto3" json:"version_profile,omitempty"`
	VersionRole         string                 `protobuf:"bytes,14,opt,name=version_role,json=versionRole,proto3" json:"version_role,omitempty"`
	VersionDeleted      string                 `protobuf:"bytes,15,opt,name=version_deleted,json=versionDeleted,proto3" json:"version_deleted,omitempty"`
	OriginNodeId        int64                  `protobuf:"varint,16,opt,name=origin_node_id,json=originNodeId,proto3" json:"origin_node_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UserUpdatedEvent) Reset() {
	*x = UserUpdatedEvent{}
	mi := &file_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdatedEvent) ProtoMessage() {}

func (x *UserUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdatedEvent.ProtoReflect.Descriptor instead.
func (*UserUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *UserUpdatedEvent) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *UserUpdatedEvent) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserUpdatedEvent) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserUpdatedEvent) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *UserUpdatedEvent) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *UserUpdatedEvent) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserUpdatedEvent) GetSystemReserved() bool {
	if x != nil {
		return x.SystemReserved
	}
	return false
}

func (x *UserUpdatedEvent) GetCreatedAtHlc() string {
	if x != nil {
		return x.CreatedAtHlc
	}
	return ""
}

func (x *UserUpdatedEvent) GetUpdatedAtHlc() string {
	if x != nil {
		return x.UpdatedAtHlc
	}
	return ""
}

func (x *UserUpdatedEvent) GetDeletedAtHlc() string {
	if x != nil {
		return x.DeletedAtHlc
	}
	return ""
}

func (x *UserUpdatedEvent) GetVersionUsername() string {
	if x != nil {
		return x.VersionUsername
	}
	return ""
}

func (x *UserUpdatedEvent) GetVersionPasswordHash() string {
	if x != nil {
		return x.VersionPasswordHash
	}
	return ""
}

func (x *UserUpdatedEvent) GetVersionProfile() string {
	if x != nil {
		return x.VersionProfile
	}
	return ""
}

func (x *UserUpdatedEvent) GetVersionRole() string {
	if x != nil {
		return x.VersionRole
	}
	return ""
}

func (x *UserUpdatedEvent) GetVersionDeleted() string {
	if x != nil {
		return x.VersionDeleted
	}
	return ""
}

func (x *UserUpdatedEvent) GetOriginNodeId() int64 {
	if x != nil {
		return x.OriginNodeId
	}
	return 0
}

type UserDeletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeletedAtHlc  string                 `protobuf:"bytes,3,opt,name=deleted_at_hlc,json=deletedAtHlc,proto3" json:"deleted_at_hlc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeletedEvent) Reset() {
	*x = UserDeletedEvent{}
	mi := &file_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeletedEvent) ProtoMessage() {}

func (x *UserDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeletedEvent.ProtoReflect.Descriptor instead.
func (*UserDeletedEvent) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{8}
}

func (x *UserDeletedEvent) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *UserDeletedEvent) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserDeletedEvent) GetDeletedAtHlc() string {
	if x != nil {
		return x.DeletedAtHlc
	}
	return ""
}

type ClusterUserRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterUserRef) Reset() {
	*x = ClusterUserRef{}
	mi := &file_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterUserRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterUserRef) ProtoMessage() {}

func (x *ClusterUserRef) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterUserRef.ProtoReflect.Descriptor instead.
func (*ClusterUserRef) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{9}
}

func (x *ClusterUserRef) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ClusterUserRef) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type MessageCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipient     *ClusterUserRef        `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	NodeId        int64                  `protobuf:"varint,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Seq           int64                  `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	Sender        *ClusterUserRef        `protobuf:"bytes,5,opt,name=sender,proto3" json:"sender,omitempty"`
	Body          []byte                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	CreatedAtHlc  string                 `protobuf:"bytes,8,opt,name=created_at_hlc,json=createdAtHlc,proto3" json:"created_at_hlc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageCreatedEvent) Reset() {
	*x = MessageCreatedEvent{}
	mi := &file_cluster_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageCreatedEvent) ProtoMessage() {}

func (x *MessageCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageCreatedEvent.ProtoReflect.Descriptor instead.
func (*MessageCreatedEvent) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{10}
}

func (x *MessageCreatedEvent) GetRecipient() *ClusterUserRef {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *MessageCreatedEvent) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *MessageCreatedEvent) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MessageCreatedEvent) GetSender() *ClusterUserRef {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *MessageCreatedEvent) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *MessageCreatedEvent) GetCreatedAtHlc() string {
	if x != nil {
		return x.CreatedAtHlc
	}
	return ""
}

type ChannelSubscribedEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Subscriber      *ClusterUserRef        `protobuf:"bytes,1,opt,name=subscriber,proto3" json:"subscriber,omitempty"`
	Channel         *ClusterUserRef        `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	SubscribedAtHlc string                 `protobuf:"bytes,5,opt,name=subscribed_at_hlc,json=subscribedAtHlc,proto3" json:"subscribed_at_hlc,omitempty"`
	OriginNodeId    int64                  `protobuf:"varint,6,opt,name=origin_node_id,json=originNodeId,proto3" json:"origin_node_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChannelSubscribedEvent) Reset() {
	*x = ChannelSubscribedEvent{}
	mi := &file_cluster_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelSubscribedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelSubscribedEvent) ProtoMessage() {}

func (x *ChannelSubscribedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelSubscribedEvent.ProtoReflect.Descriptor instead.
func (*ChannelSubscribedEvent) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{11}
}

func (x *ChannelSubscribedEvent) GetSubscriber() *ClusterUserRef {
	if x != nil {
		return x.Subscriber
	}
	return nil
}

func (x *ChannelSubscribedEvent) GetChannel() *ClusterUserRef {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *ChannelSubscribedEvent) GetSubscribedAtHlc() string {
	if x != nil {
		return x.SubscribedAtHlc
	}
	return ""
}

func (x *ChannelSubscribedEvent) GetOriginNodeId() int64 {
	if x != nil {
		return x.OriginNodeId
	}
	return 0
}

type ChannelUnsubscribedEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Subscriber      *ClusterUserRef        `protobuf:"bytes,1,opt,name=subscriber,proto3" json:"subscriber,omitempty"`
	Channel         *ClusterUserRef        `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	SubscribedAtHlc string                 `protobuf:"bytes,5,opt,name=subscribed_at_hlc,json=subscribedAtHlc,proto3" json:"subscribed_at_hlc,omitempty"`
	DeletedAtHlc    string                 `protobuf:"bytes,6,opt,name=deleted_at_hlc,json=deletedAtHlc,proto3" json:"deleted_at_hlc,omitempty"`
	OriginNodeId    int64                  `protobuf:"varint,7,opt,name=origin_node_id,json=originNodeId,proto3" json:"origin_node_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChannelUnsubscribedEvent) Reset() {
	*x = ChannelUnsubscribedEvent{}
	mi := &file_cluster_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelUnsubscribedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelUnsubscribedEvent) ProtoMessage() {}

func (x *ChannelUnsubscribedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelUnsubscribedEvent.ProtoReflect.Descriptor instead.
func (*ChannelUnsubscribedEvent) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{12}
}

func (x *ChannelUnsubscribedEvent) GetSubscriber() *ClusterUserRef {
	if x != nil {
		return x.Subscriber
	}
	return nil
}

func (x *ChannelUnsubscribedEvent) GetChannel() *ClusterUserRef {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *ChannelUnsubscribedEvent) GetSubscribedAtHlc() string {
	if x != nil {
		return x.SubscribedAtHlc
	}
	return ""
}

func (x *ChannelUnsubscribedEvent) GetDeletedAtHlc() string {
	if x != nil {
		return x.DeletedAtHlc
	}
	return ""
}

func (x *ChannelUnsubscribedEvent) GetOriginNodeId() int64 {
	if x != nil {
		return x.OriginNodeId
	}
	return 0
}

type PullEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginNodeId  int64                  `protobuf:"varint,1,opt,name=origin_node_id,json=originNodeId,proto3" json:"origin_node_id,omitempty"`
	AfterEventId  uint64                 `protobuf:"varint,2,opt,name=after_event_id,json=afterEventId,proto3" json:"after_event_id,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	RequestId     uint64                 `protobuf:"varint,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullEvents) Reset() {
	*x = PullEvents{}
	mi := &file_cluster_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullEvents) ProtoMessage() {}

func (x *PullEvents) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullEvents.ProtoReflect.Descriptor instead.
func (*PullEvents) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{13}
}

func (x *PullEvents) GetOriginNodeId() int64 {
	if x != nil {
		return x.OriginNodeId
	}
	return 0
}

func (x *PullEvents) GetAfterEventId() uint64 {
	if x != nil {
		return x.AfterEventId
	}
	return 0
}

func (x *PullEvents) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PullEvents) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type SnapshotDigest struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	SnapshotVersion string                     `protobuf:"bytes,1,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	Partitions      []*SnapshotPartitionDigest `protobuf:"bytes,2,rep,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SnapshotDigest) Reset() {
	*x = SnapshotDigest{}
	mi := &file_cluster_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotDigest) ProtoMessage() {}

func (x *SnapshotDigest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotDigest.ProtoReflect.Descriptor instead.
func (*SnapshotDigest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{14}
}

func (x *SnapshotDigest) GetSnapshotVersion() string {
	if x != nil {
		return x.SnapshotVersion
	}
	return ""
}

func (x *SnapshotDigest) GetPartitions() []*SnapshotPartitionDigest {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type SnapshotChunk struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Partition       string                 `protobuf:"bytes,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Rows            []*SnapshotRow         `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	SnapshotVersion string                 `protobuf:"bytes,3,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	Kind            SnapshotPartitionKind  `protobuf:"varint,4,opt,name=kind,proto3,enum=notifier.cluster.v1.SnapshotPartitionKind" json:"kind,omitempty"`
	Request         bool                   `protobuf:"varint,5,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SnapshotChunk) Reset() {
	*x = SnapshotChunk{}
	mi := &file_cluster_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotChunk) ProtoMessage() {}

func (x *SnapshotChunk) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotChunk.ProtoReflect.Descriptor instead.
func (*SnapshotChunk) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{15}
}

func (x *SnapshotChunk) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *SnapshotChunk) GetRows() []*SnapshotRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *SnapshotChunk) GetSnapshotVersion() string {
	if x != nil {
		return x.SnapshotVersion
	}
	return ""
}

func (x *SnapshotChunk) GetKind() SnapshotPartitionKind {
	if x != nil {
		return x.Kind
	}
	return SnapshotPartitionKind_SNAPSHOT_PARTITION_KIND_UNSPECIFIED
}

func (x *SnapshotChunk) GetRequest() bool {
	if x != nil {
		return x.Request
	}
	return false
}

type SnapshotPartitionDigest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     string                 `protobuf:"bytes,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Kind          SnapshotPartitionKind  `protobuf:"varint,2,opt,name=kind,proto3,enum=notifier.cluster.v1.SnapshotPartitionKind" json:"kind,omitempty"`
	RowCount      uint64                 `protobuf:"varint,3,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	Hash          []byte                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotPartitionDigest) Reset() {
	*x = SnapshotPartitionDigest{}
	mi := &file_cluster_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotPartitionDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotPartitionDigest) ProtoMessage() {}

func (x *SnapshotPartitionDigest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotPartitionDigest.ProtoReflect.Descriptor instead.
func (*SnapshotPartitionDigest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{16}
}

func (x *SnapshotPartitionDigest) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *SnapshotPartitionDigest) GetKind() SnapshotPartitionKind {
	if x != nil {
		return x.Kind
	}
	return SnapshotPartitionKind_SNAPSHOT_PARTITION_KIND_UNSPECIFIED
}

func (x *SnapshotPartitionDigest) GetRowCount() uint64 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *SnapshotPartitionDigest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type SnapshotRow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*SnapshotRow_User
	//	*SnapshotRow_Tombstone
	//	*SnapshotRow_Message
	//	*SnapshotRow_Subscription
	Body          isSnapshotRow_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRow) Reset() {
	*x = SnapshotRow{}
	mi := &file_cluster_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRow) ProtoMessage() {}

func (x *SnapshotRow) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRow.ProtoReflect.Descriptor instead.
func (*SnapshotRow) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{17}
}

func (x *SnapshotRow) GetBody() isSnapshotRow_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SnapshotRow) GetUser() *SnapshotUserRow {
	if x != nil {
		if x, ok := x.Body.(*SnapshotRow_User); ok {
			return x.User
		}
	}
	return nil
}

func (x *SnapshotRow) GetTombstone() *SnapshotTombstoneRow {
	if x != nil {
		if x, ok := x.Body.(*SnapshotRow_Tombstone); ok {
			return x.Tombstone
		}
	}
	return nil
}

func (x *SnapshotRow) GetMessage() *SnapshotMessageRow {
	if x != nil {
		if x, ok := x.Body.(*SnapshotRow_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *SnapshotRow) GetSubscription() *SnapshotSubscriptionRow {
	if x != nil {
		if x, ok := x.Body.(*SnapshotRow_Subscription); ok {
			return x.Subscription
		}
	}
	return nil
}

type isSnapshotRow_Body interface {
	isSnapshotRow_Body()
}

type SnapshotRow_User struct {
	User *SnapshotUserRow `protobuf:"bytes,1,opt,name=user,proto3,oneof"`
}

type SnapshotRow_Tombstone struct {
	Tombstone *SnapshotTombstoneRow `protobuf:"bytes,2,opt,name=tombstone,proto3,oneof"`
}

type SnapshotRow_Message struct {
	Message *SnapshotMessageRow `protobuf:"bytes,3,opt,name=message,proto3,oneof"`
}

type SnapshotRow_Subscription struct {
	Subscription *SnapshotSubscriptionRow `protobuf:"bytes,4,opt,name=subscription,proto3,oneof"`
}

func (*SnapshotRow_User) isSnapshotRow_Body() {}

func (*SnapshotRow_Tombstone) isSnapshotRow_Body() {}

func (*SnapshotRow_Message) isSnapshotRow_Body() {}

func (*SnapshotRow_Subscription) isSnapshotRow_Body() {}

type SnapshotUserRow struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NodeId              int64                  `protobuf:"varint,16,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Username            string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash        string                 `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Profile             string                 `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	Role                string                 `protobuf:"bytes,13,opt,name=role,proto3" json:"role,omitempty"`
	SystemReserved      bool                   `protobuf:"varint,14,opt,name=system_reserved,json=systemReserved,proto3" json:"system_reserved,omitempty"`
	CreatedAtHlc        string                 `protobuf:"bytes,5,opt,name=created_at_hlc,json=createdAtHlc,proto3" json:"created_at_hlc,omitempty"`
	UpdatedAtHlc        string                 `protobuf:"bytes,6,opt,name=updated_at_hlc,json=updatedAtHlc,proto3" json:"updated_at_hlc,omitempty"`
	DeletedAtHlc        string                 `protobuf:"bytes,7,opt,name=deleted_at_hlc,json=deletedAtHlc,proto3" json:"deleted_at_hlc,omitempty"`
	VersionUsername     string                 `protobuf:"bytes,8,opt,name=version_username,json=versionUsername,proto3" json:"version_username,omitempty"`
	VersionPasswordHash string                 `protobuf:"bytes,9,opt,name=version_password_hash,json=versionPasswordHash,proto3" json:"version_password_hash,omitempty"`
	VersionProfile      string                 `protobuf:"bytes,10,opt,name=version_profile,json=versionProfile,proto3" json:"version_profile,omitempty"`
	VersionRole         string                 `protobuf:"bytes,15,opt,name=version_role,json=versionRole,proto3" json:"version_role,omitempty"`
	VersionDeleted      string                 `protobuf:"bytes,11,opt,name=version_deleted,json=versionDeleted,proto3" json:"version_deleted,omitempty"`
	OriginNodeId        int64                  `protobuf:"varint,12,opt,name=origin_node_id,json=originNodeId,proto3" json:"origin_node_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SnapshotUserRow) Reset() {
	*x = SnapshotUserRow{}
	mi := &file_cluster_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotUserRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotUserRow) ProtoMessage() {}

func (x *SnapshotUserRow) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotUserRow.ProtoReflect.Descriptor instead.
func (*SnapshotUserRow) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{18}
}

func (x *SnapshotUserRow) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SnapshotUserRow) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *SnapshotUserRow) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SnapshotUserRow) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *SnapshotUserRow) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *SnapshotUserRow) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *SnapshotUserRow) GetSystemReserved() bool {
	if x != nil {
		return x.SystemReserved
	}
	return false
}

func (x *SnapshotUserRow) GetCreatedAtHlc() string {
	if x != nil {
		return x.CreatedAtHlc
	}
	return ""
}

func (x *SnapshotUserRow) GetUpdatedAtHlc() string {
	if x != nil {
		return x.UpdatedAtHlc
	}
	return ""
}

func (x *SnapshotUserRow) GetDeletedAtHlc() string {
	if x != nil {
		return x.DeletedAtHlc
	}
	return ""
}

func (x *SnapshotUserRow) GetVersionUsername() string {
	if x != nil {
		return x.VersionUsername
	}
	return ""
}

func (x *SnapshotUserRow) GetVersionPasswordHash() string {
	if x != nil {
		return x.VersionPasswordHash
	}
	return ""
}

func (x *SnapshotUserRow) GetVersionProfile() string {
	if x != nil {
		return x.VersionProfile
	}
	return ""
}

func (x *SnapshotUserRow) GetVersionRole() string {
	if x != nil {
		return x.VersionRole
	}
	return ""
}

func (x *SnapshotUserRow) GetVersionDeleted() string {
	if x != nil {
		return x.VersionDeleted
	}
	return ""
}

func (x *SnapshotUserRow) GetOriginNodeId() int64 {
	if x != nil {
		return x.OriginNodeId
	}
	return 0
}

type SnapshotTombstoneRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId      int64                  `protobuf:"varint,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	DeletedAtHlc  string                 `protobuf:"bytes,3,opt,name=deleted_at_hlc,json=deletedAtHlc,proto3" json:"deleted_at_hlc,omitempty"`
	OriginNodeId  int64                  `protobuf:"varint,4,opt,name=origin_node_id,json=originNodeId,proto3" json:"origin_node_id,omitempty"`
	EntityNodeId  int64                  `protobuf:"varint,5,opt,name=entity_node_id,json=entityNodeId,proto3" json:"entity_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotTombstoneRow) Reset() {
	*x = SnapshotTombstoneRow{}
	mi := &file_cluster_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotTombstoneRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotTombstoneRow) ProtoMessage() {}

func (x *SnapshotTombstoneRow) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotTombstoneRow.ProtoReflect.Descriptor instead.
func (*SnapshotTombstoneRow) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{19}
}

func (x *SnapshotTombstoneRow) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *SnapshotTombstoneRow) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *SnapshotTombstoneRow) GetDeletedAtHlc() string {
	if x != nil {
		return x.DeletedAtHlc
	}
	return ""
}

func (x *SnapshotTombstoneRow) GetOriginNodeId() int64 {
	if x != nil {
		return x.OriginNodeId
	}
	return 0
}

func (x *SnapshotTombstoneRow) GetEntityNodeId() int64 {
	if x != nil {
		return x.EntityNodeId
	}
	return 0
}

type SnapshotMessageRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipient     *ClusterUserRef        `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	NodeId        int64                  `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Sender        *ClusterUserRef        `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	CreatedAtHlc  string                 `protobuf:"bytes,6,opt,name=created_at_hlc,json=createdAtHlc,proto3" json:"created_at_hlc,omitempty"`
	Seq           int64                  `protobuf:"varint,7,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotMessageRow) Reset() {
	*x = SnapshotMessageRow{}
	mi := &file_cluster_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotMessageRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotMessageRow) ProtoMessage() {}

func (x *SnapshotMessageRow) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotMessageRow.ProtoReflect.Descriptor instead.
func (*SnapshotMessageRow) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{20}
}

func (x *SnapshotMessageRow) GetRecipient() *ClusterUserRef {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *SnapshotMessageRow) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *SnapshotMessageRow) GetSender() *ClusterUserRef {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *SnapshotMessageRow) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SnapshotMessageRow) GetCreatedAtHlc() string {
	if x != nil {
		return x.CreatedAtHlc
	}
	return ""
}

func (x *SnapshotMessageRow) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type SnapshotSubscriptionRow struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Subscriber      *ClusterUserRef        `protobuf:"bytes,1,opt,name=subscriber,proto3" json:"subscriber,omitempty"`
	Channel         *ClusterUserRef        `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	SubscribedAtHlc string                 `protobuf:"bytes,5,opt,name=subscribed_at_hlc,json=subscribedAtHlc,proto3" json:"subscribed_at_hlc,omitempty"`
	DeletedAtHlc    string                 `protobuf:"bytes,6,opt,name=deleted_at_hlc,json=deletedAtHlc,proto3" json:"deleted_at_hlc,omitempty"`
	OriginNodeId    int64                  `protobuf:"varint,7,opt,name=origin_node_id,json=originNodeId,proto3" json:"origin_node_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SnapshotSubscriptionRow) Reset() {
	*x = SnapshotSubscriptionRow{}
	mi := &file_cluster_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotSubscriptionRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotSubscriptionRow) ProtoMessage() {}

func (x *SnapshotSubscriptionRow) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotSubscriptionRow.ProtoReflect.Descriptor instead.
func (*SnapshotSubscriptionRow) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{21}
}

func (x *SnapshotSubscriptionRow) GetSubscriber() *ClusterUserRef {
	if x != nil {
		return x.Subscriber
	}
	return nil
}

func (x *SnapshotSubscriptionRow) GetChannel() *ClusterUserRef {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *SnapshotSubscriptionRow) GetSubscribedAtHlc() string {
	if x != nil {
		return x.SubscribedAtHlc
	}
	return ""
}

func (x *SnapshotSubscriptionRow) GetDeletedAtHlc() string {
	if x != nil {
		return x.DeletedAtHlc
	}
	return ""
}

func (x *SnapshotSubscriptionRow) GetOriginNodeId() int64 {
	if x != nil {
		return x.OriginNodeId
	}
	return 0
}

type TimeSyncRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ClientSendTimeMs int64                  `protobuf:"varint,2,opt,name=client_send_time_ms,json=clientSendTimeMs,proto3" json:"client_send_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TimeSyncRequest) Reset() {
	*x = TimeSyncRequest{}
	mi := &file_cluster_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSyncRequest) ProtoMessage() {}

func (x *TimeSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSyncRequest.ProtoReflect.Descriptor instead.
func (*TimeSyncRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{22}
}

func (x *TimeSyncRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *TimeSyncRequest) GetClientSendTimeMs() int64 {
	if x != nil {
		return x.ClientSendTimeMs
	}
	return 0
}

type TimeSyncResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RequestId           uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ClientSendTimeMs    int64                  `protobuf:"varint,2,opt,name=client_send_time_ms,json=clientSendTimeMs,proto3" json:"client_send_time_ms,omitempty"`
	ServerReceiveTimeMs int64                  `protobuf:"varint,3,opt,name=server_receive_time_ms,json=serverReceiveTimeMs,proto3" json:"server_receive_time_ms,omitempty"`
	ServerSendTimeMs    int64                  `protobuf:"varint,4,opt,name=server_send_time_ms,json=serverSendTimeMs,proto3" json:"server_send_time_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TimeSyncResponse) Reset() {
	*x = TimeSyncResponse{}
	mi := &file_cluster_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSyncResponse) ProtoMessage() {}

func (x *TimeSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSyncResponse.ProtoReflect.Descriptor instead.
func (*TimeSyncResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{23}
}

func (x *TimeSyncResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *TimeSyncResponse) GetClientSendTimeMs() int64 {
	if x != nil {
		return x.ClientSendTimeMs
	}
	return 0
}

func (x *TimeSyncResponse) GetServerReceiveTimeMs() int64 {
	if x != nil {
		return x.ServerReceiveTimeMs
	}
	return 0
}

func (x *TimeSyncResponse) GetServerSendTimeMs() int64 {
	if x != nil {
		return x.ServerSendTimeMs
	}
	return 0
}

type RoutingUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginNodeId  int64                  `protobuf:"varint,1,opt,name=origin_node_id,json=originNodeId,proto3" json:"origin_node_id,omitempty"`
	Generation    uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	Routes        []*RouteAdvertisement  `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingUpdate) Reset() {
	*x = RoutingUpdate{}
	mi := &file_cluster_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingUpdate) ProtoMessage() {}

func (x *RoutingUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingUpdate.ProtoReflect.Descriptor instead.
func (*RoutingUpdate) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{24}
}

func (x *RoutingUpdate) GetOriginNodeId() int64 {
	if x != nil {
		return x.OriginNodeId
	}
	return 0
}

func (x *RoutingUpdate) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *RoutingUpdate) GetRoutes() []*RouteAdvertisement {
	if x != nil {
		return x.Routes
	}
	return nil
}

type RouteAdvertisement struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DestinationNodeId int64                  `protobuf:"varint,1,opt,name=destination_node_id,json=destinationNodeId,proto3" json:"destination_node_id,omitempty"`
	Reachable         bool                   `protobuf:"varint,2,opt,name=reachable,proto3" json:"reachable,omitempty"`
	TotalCostMs       uint32                 `protobuf:"varint,3,opt,name=total_cost_ms,json=totalCostMs,proto3" json:"total_cost_ms,omitempty"`
	ResidualCostMs    uint32                 `protobuf:"varint,4,opt,name=residual_cost_ms,json=residualCostMs,proto3" json:"residual_cost_ms,omitempty"`
	ResidualJitterMs  uint32                 `protobuf:"varint,5,opt,name=residual_jitter_ms,json=residualJitterMs,proto3" json:"residual_jitter_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RouteAdvertisement) Reset() {
	*x = RouteAdvertisement{}
	mi := &file_cluster_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteAdvertisement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteAdvertisement) ProtoMessage() {}

func (x *RouteAdvertisement) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteAdvertisement.ProtoReflect.Descriptor instead.
func (*RouteAdvertisement) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{25}
}

func (x *RouteAdvertisement) GetDestinationNodeId() int64 {
	if x != nil {
		return x.DestinationNodeId
	}
	return 0
}

func (x *RouteAdvertisement) GetReachable() bool {
	if x != nil {
		return x.Reachable
	}
	return false
}

func (x *RouteAdvertisement) GetTotalCostMs() uint32 {
	if x != nil {
		return x.TotalCostMs
	}
	return 0
}

func (x *RouteAdvertisement) GetResidualCostMs() uint32 {
	if x != nil {
		return x.ResidualCostMs
	}
	return 0
}

func (x *RouteAdvertisement) GetResidualJitterMs() uint32 {
	if x != nil {
		return x.ResidualJitterMs
	}
	return 0
}

type TransientPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PacketId      uint64                 `protobuf:"varint,1,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"`
	SourceNodeId  int64                  `protobuf:"varint,2,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	TargetNodeId  int64                  `protobuf:"varint,3,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	Recipient     *ClusterUserRef        `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Sender        *ClusterUserRef        `protobuf:"bytes,6,opt,name=sender,proto3" json:"sender,omitempty"`
	Body          []byte                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	DeliveryMode  ClusterDeliveryMode    `protobuf:"varint,8,opt,name=delivery_mode,json=deliveryMode,proto3,enum=notifier.cluster.v1.ClusterDeliveryMode" json:"delivery_mode,omitempty"`
	TtlHops       uint32                 `protobuf:"varint,9,opt,name=ttl_hops,json=ttlHops,proto3" json:"ttl_hops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransientPacket) Reset() {
	*x = TransientPacket{}
	mi := &file_cluster_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransientPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransientPacket) ProtoMessage() {}

func (x *TransientPacket) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransientPacket.ProtoReflect.Descriptor instead.
func (*TransientPacket) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{26}
}

func (x *TransientPacket) GetPacketId() uint64 {
	if x != nil {
		return x.PacketId
	}
	return 0
}

func (x *TransientPacket) GetSourceNodeId() int64 {
	if x != nil {
		return x.SourceNodeId
	}
	return 0
}

func (x *TransientPacket) GetTargetNodeId() int64 {
	if x != nil {
		return x.TargetNodeId
	}
	return 0
}

func (x *TransientPacket) GetRecipient() *ClusterUserRef {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *TransientPacket) GetSender() *ClusterUserRef {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *TransientPacket) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *TransientPacket) GetDeliveryMode() ClusterDeliveryMode {
	if x != nil {
		return x.DeliveryMode
	}
	return ClusterDeliveryMode_CLUSTER_DELIVERY_MODE_UNSPECIFIED
}

func (x *TransientPacket) GetTtlHops() uint32 {
	if x != nil {
		return x.TtlHops
	}
	return 0
}

var File_cluster_proto protoreflect.FileDescriptor

const file_cluster_proto_rawDesc = "" +
	"\n" +
	"\rcluster.proto\x12\x13notifier.cluster.v1\"\xcd\x06\n" +
	"\bEnvelope\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x1e\n" +
	"\vsent_at_hlc\x18\x03 \x01(\tR\tsentAtHlc\x122\n" +
	"\x05hello\x18\x04 \x01(\v2\x1a.notifier.cluster.v1.HelloH\x00R\x05hello\x12,\n" +
	"\x03ack\x18\x05 \x01(\v2\x18.notifier.cluster.v1.AckH\x00R\x03ack\x12B\n" +
	"\vevent_batch\x18\x06 \x01(\v2\x1f.notifier.cluster.v1.EventBatchH\x00R\n" +
	"eventBatch\x12B\n" +
	"\vpull_events\x18\a \x01(\v2\x1f.notifier.cluster.v1.PullEventsH\x00R\n" +
	"pullEvents\x12N\n" +
	"\x0fsnapshot_digest\x18\b \x01(\v2#.notifier.cluster.v1.SnapshotDigestH\x00R\x0esnapshotDigest\x12K\n" +
	"\x0esnapshot_chunk\x18\t \x01(\v2\".notifier.cluster.v1.SnapshotChunkH\x00R\rsnapshotChunk\x12R\n" +
	"\x11time_sync_request\x18\n" +
	" \x01(\v2$.notifier.cluster.v1.TimeSyncRequestH\x00R\x0ftimeSyncRequest\x12U\n" +
	"\x12time_sync_response\x18\v \x01(\v2%.notifier.cluster.v1.TimeSyncResponseH\x00R\x10timeSyncResponse\x12K\n" +
	"\x0erouting_update\x18\r \x01(\v2\".notifier.cluster.v1.RoutingUpdateH\x00R\rroutingUpdate\x12Q\n" +
	"\x10transient_packet\x18\x0e \x01(\v2$.notifier.cluster.v1.TransientPacketH\x00R\x0ftransientPacket\x12\x12\n" +
	"\x04hmac\x18\f \x01(\fR\x04hmacB\x06\n" +
	"\x04body\"\xbf\x03\n" +
	"\x05Hello\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\x12%\n" +
	"\x0eadvertise_addr\x18\x02 \x01(\tR\radvertiseAddr\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\tR\x0fprotocolVersion\x12L\n" +
	"\x0forigin_progress\x18\x04 \x03(\v2#.notifier.cluster.v1.OriginProgressR\x0eoriginProgress\x12)\n" +
	"\x10snapshot_version\x18\x05 \x01(\tR\x0fsnapshotVersion\x12.\n" +
	"\x13message_window_size\x18\x06 \x01(\rR\x11messageWindowSize\x12)\n" +
	"\x10supports_routing\x18\a \x01(\bR\x0fsupportsRouting\x12#\n" +
	"\rconnection_id\x18\b \x01(\x04R\fconnectionId\x12&\n" +
	"\x0fsmoothed_rtt_ms\x18\t \x01(\rR\rsmoothedRttMs\x12*\n" +
	"\x11jitter_penalty_ms\x18\n" +
	" \x01(\rR\x0fjitterPenaltyMs\"Z\n" +
	"\x0eOriginProgress\x12$\n" +
	"\x0eorigin_node_id\x18\x01 \x01(\x03R\foriginNodeId\x12\"\n" +
	"\rlast_event_id\x18\x02 \x01(\x04R\vlastEventId\"j\n" +
	"\x03Ack\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\x12$\n" +
	"\x0eorigin_node_id\x18\x02 \x01(\x03R\foriginNodeId\x12$\n" +
	"\x0eacked_event_id\x18\x03 \x01(\x04R\fackedEventId\"\x98\x01\n" +
	"\n" +
	"EventBatch\x12<\n" +
	"\x06events\x18\x01 \x03(\v2$.notifier.cluster.v1.ReplicatedEventR\x06events\x12&\n" +
	"\x0fpull_request_id\x18\x02 \x01(\x04R\rpullRequestId\x12$\n" +
	"\x0eorigin_node_id\x18\x03 \x01(\x03R\foriginNodeId\"\xdd\x05\n" +
	"\x0fReplicatedEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12%\n" +
	"\x0eaggregate_type\x18\x02 \x01(\tR\raggregateType\x12*\n" +
	"\x11aggregate_node_id\x18\x03 \x01(\x03R\x0faggregateNodeId\x12!\n" +
	"\faggregate_id\x18\x04 \x01(\x03R\vaggregateId\x12\x10\n" +
	"\x03hlc\x18\x05 \x01(\tR\x03hlc\x12$\n" +
	"\x0eorigin_node_id\x18\x06 \x01(\x03R\foriginNodeId\x12J\n" +
	"\fuser_created\x18\a \x01(\v2%.notifier.cluster.v1.UserCreatedEventH\x00R\vuserCreated\x12J\n" +
	"\fuser_updated\x18\b \x01(\v2%.notifier.cluster.v1.UserUpdatedEventH\x00R\vuserUpdated\x12J\n" +
	"\fuser_deleted\x18\t \x01(\v2%.notifier.cluster.v1.UserDeletedEventH\x00R\vuserDeleted\x12S\n" +
	"\x0fmessage_created\x18\n" +
	" \x01(\v2(.notifier.cluster.v1.MessageCreatedEventH\x00R\x0emessageCreated\x12\\\n" +
	"\x12channel_subscribed\x18\v \x01(\v2+.notifier.cluster.v1.ChannelSubscribedEventH\x00R\x11channelSubscribed\x12b\n" +
	"\x14channel_unsubscribed\x18\f \x01(\v2-.notifier.cluster.v1.ChannelUnsubscribedEventH\x00R\x13channelUnsubscribedB\x06\n" +
	"\x04body\"\xf9\x03\n" +
	"\x10UserCreatedEvent\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12#\n" +
	"\rpassword_hash\x18\x04 \x01(\tR\fpasswordHash\x12\x18\n" +
	"\aprofile\x18\x05 \x01(\tR\aprofile\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x12'\n" +
	"\x0fsystem_reserved\x18\a \x01(\bR\x0esystemReserved\x12$\n" +
	"\x0ecreated_at_hlc\x18\b \x01(\tR\fcreatedAtHlc\x12$\n" +
	"\x0eupdated_at_hlc\x18\t \x01(\tR\fupdatedAtHlc\x12)\n" +
	"\x10version_username\x18\n" +
	" \x01(\tR\x0fversionUsername\x122\n" +
	"\x15version_password_hash\x18\v \x01(\tR\x13versionPasswordHash\x12'\n" +
	"\x0fversion_profile\x18\f \x01(\tR\x0eversionProfile\x12!\n" +
	"\fversion_role\x18\r \x01(\tR\vversionRole\x12$\n" +
	"\x0eorigin_node_id\x18\x0e \x01(\x03R\foriginNodeId\"\xc8\x04\n" +
	"\x10UserUpdatedEvent\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12#\n" +
	"\rpassword_hash\x18\x04 \x01(\tR\fpasswordHash\x12\x18\n" +
	"\aprofile\x18\x05 \x01(\tR\aprofile\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x12'\n" +
	"\x0fsystem_reserved\x18\a \x01(\bR\x0esystemReserved\x12$\n" +
	"\x0ecreated_at_hlc\x18\b \x01(\tR\fcreatedAtHlc\x12$\n" +
	"\x0eupdated_at_hlc\x18\t \x01(\tR\fupdatedAtHlc\x12$\n" +
	"\x0edeleted_at_hlc\x18\n" +
	" \x01(\tR\fdeletedAtHlc\x12)\n" +
	"\x10version_username\x18\v \x01(\tR\x0fversionUsername\x122\n" +
	"\x15version_password_hash\x18\f \x01(\tR\x13versionPasswordHash\x12'\n" +
	"\x0fversion_profile\x18\r \x01(\tR\x0eversionProfile\x12!\n" +
	"\fversion_role\x18\x0e \x01(\tR\vversionRole\x12'\n" +
	"\x0fversion_deleted\x18\x0f \x01(\tR\x0eversionDeleted\x12$\n" +
	"\x0eorigin_node_id\x18\x10 \x01(\x03R\foriginNodeId\"j\n" +
	"\x10UserDeletedEvent\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12$\n" +
	"\x0edeleted_at_hlc\x18\x03 \x01(\tR\fdeletedAtHlc\"B\n" +
	"\x0eClusterUserRef\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\xfa\x01\n" +
	"\x13MessageCreatedEvent\x12A\n" +
	"\trecipient\x18\x01 \x01(\v2#.notifier.cluster.v1.ClusterUserRefR\trecipient\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\x03R\x06nodeId\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x03R\x03seq\x12;\n" +
	"\x06sender\x18\x05 \x01(\v2#.notifier.cluster.v1.ClusterUserRefR\x06sender\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\x12$\n" +
	"\x0ecreated_at_hlc\x18\b \x01(\tR\fcreatedAtHlc\"\xee\x01\n" +
	"\x16ChannelSubscribedEvent\x12C\n" +
	"\n" +
	"subscriber\x18\x01 \x01(\v2#.notifier.cluster.v1.ClusterUserRefR\n" +
	"subscriber\x12=\n" +
	"\achannel\x18\x03 \x01(\v2#.notifier.cluster.v1.ClusterUserRefR\achannel\x12*\n" +
	"\x11subscribed_at_hlc\x18\x05 \x01(\tR\x0fsubscribedAtHlc\x12$\n" +
	"\x0eorigin_node_id\x18\x06 \x01(\x03R\foriginNodeId\"\x96\x02\n" +
	"\x18ChannelUnsubscribedEvent\x12C\n" +
	"\n" +
	"subscriber\x18\x01 \x01(\v2#.notifier.cluster.v1.ClusterUserRefR\n" +
	"subscriber\x12=\n" +
	"\achannel\x18\x03 \x01(\v2#.notifier.cluster.v1.ClusterUserRefR\achannel\x12*\n" +
	"\x11subscribed_at_hlc\x18\x05 \x01(\tR\x0fsubscribedAtHlc\x12$\n" +
	"\x0edeleted_at_hlc\x18\x06 \x01(\tR\fdeletedAtHlc\x12$\n" +
	"\x0eorigin_node_id\x18\a \x01(\x03R\foriginNodeId\"\x8d\x01\n" +
	"\n" +
	"PullEvents\x12$\n" +
	"\x0eorigin_node_id\x18\x01 \x01(\x03R\foriginNodeId\x12$\n" +
	"\x0eafter_event_id\x18\x02 \x01(\x04R\fafterEventId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\x04R\trequestId\"\x89\x01\n" +
	"\x0eSnapshotDigest\x12)\n" +
	"\x10snapshot_version\x18\x01 \x01(\tR\x0fsnapshotVersion\x12L\n" +
	"\n" +
	"partitions\x18\x02 \x03(\v2,.notifier.cluster.v1.SnapshotPartitionDigestR\n" +
	"partitions\"\xe8\x01\n" +
	"\rSnapshotChunk\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\tR\tpartition\x124\n" +
	"\x04rows\x18\x02 \x03(\v2 .notifier.cluster.v1.SnapshotRowR\x04rows\x12)\n" +
	"\x10snapshot_version\x18\x03 \x01(\tR\x0fsnapshotVersion\x12>\n" +
	"\x04kind\x18\x04 \x01(\x0e2*.notifier.cluster.v1.SnapshotPartitionKindR\x04kind\x12\x18\n" +
	"\arequest\x18\x05 \x01(\bR\arequest\"\xa8\x01\n" +
	"\x17SnapshotPartitionDigest\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\tR\tpartition\x12>\n" +
	"\x04kind\x18\x02 \x01(\x0e2*.notifier.cluster.v1.SnapshotPartitionKindR\x04kind\x12\x1b\n" +
	"\trow_count\x18\x03 \x01(\x04R\browCount\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\fR\x04hash\"\xb5\x02\n" +
	"\vSnapshotRow\x12:\n" +
	"\x04user\x18\x01 \x01(\v2$.notifier.cluster.v1.SnapshotUserRowH\x00R\x04user\x12I\n" +
	"\ttombstone\x18\x02 \x01(\v2).notifier.cluster.v1.SnapshotTombstoneRowH\x00R\ttombstone\x12C\n" +
	"\amessage\x18\x03 \x01(\v2'.notifier.cluster.v1.SnapshotMessageRowH\x00R\amessage\x12R\n" +
	"\fsubscription\x18\x04 \x01(\v2,.notifier.cluster.v1.SnapshotSubscriptionRowH\x00R\fsubscriptionB\x06\n" +
	"\x04body\"\xc7\x04\n" +
	"\x0fSnapshotUserRow\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\anode_id\x18\x10 \x01(\x03R\x06nodeId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12#\n" +
	"\rpassword_hash\x18\x03 \x01(\tR\fpasswordHash\x12\x18\n" +
	"\aprofile\x18\x04 \x01(\tR\aprofile\x12\x12\n" +
	"\x04role\x18\r \x01(\tR\x04role\x12'\n" +
	"\x0fsystem_reserved\x18\x0e \x01(\bR\x0esystemReserved\x12$\n" +
	"\x0ecreated_at_hlc\x18\x05 \x01(\tR\fcreatedAtHlc\x12$\n" +
	"\x0eupdated_at_hlc\x18\x06 \x01(\tR\fupdatedAtHlc\x12$\n" +
	"\x0edeleted_at_hlc\x18\a \x01(\tR\fdeletedAtHlc\x12)\n" +
	"\x10version_username\x18\b \x01(\tR\x0fversionUsername\x122\n" +
	"\x15version_password_hash\x18\t \x01(\tR\x13versionPasswordHash\x12'\n" +
	"\x0fversion_profile\x18\n" +
	" \x01(\tR\x0eversionProfile\x12!\n" +
	"\fversion_role\x18\x0f \x01(\tR\vversionRole\x12'\n" +
	"\x0fversion_deleted\x18\v \x01(\tR\x0eversionDeleted\x12$\n" +
	"\x0eorigin_node_id\x18\f \x01(\x03R\foriginNodeId\"\xc6\x01\n" +
	"\x14SnapshotTombstoneRow\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\x03R\bentityId\x12$\n" +
	"\x0edeleted_at_hlc\x18\x03 \x01(\tR\fdeletedAtHlc\x12$\n" +
	"\x0eorigin_node_id\x18\x04 \x01(\x03R\foriginNodeId\x12$\n" +
	"\x0eentity_node_id\x18\x05 \x01(\x03R\fentityNodeId\"\xf9\x01\n" +
	"\x12SnapshotMessageRow\x12A\n" +
	"\trecipient\x18\x01 \x01(\v2#.notifier.cluster.v1.ClusterUserRefR\trecipient\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\x03R\x06nodeId\x12;\n" +
	"\x06sender\x18\x03 \x01(\v2#.notifier.cluster.v1.ClusterUserRefR\x06sender\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12$\n" +
	"\x0ecreated_at_hlc\x18\x06 \x01(\tR\fcreatedAtHlc\x12\x10\n" +
	"\x03seq\x18\a \x01(\x03R\x03seq\"\x95\x02\n" +
	"\x17SnapshotSubscriptionRow\x12C\n" +
	"\n" +
	"subscriber\x18\x01 \x01(\v2#.notifier.cluster.v1.ClusterUserRefR\n" +
	"subscriber\x12=\n" +
	"\achannel\x18\x03 \x01(\v2#.notifier.cluster.v1.ClusterUserRefR\achannel\x12*\n" +
	"\x11subscribed_at_hlc\x18\x05 \x01(\tR\x0fsubscribedAtHlc\x12$\n" +
	"\x0edeleted_at_hlc\x18\x06 \x01(\tR\fdeletedAtHlc\x12$\n" +
	"\x0eorigin_node_id\x18\a \x01(\x03R\foriginNodeId\"_\n" +
	"\x0fTimeSyncRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12-\n" +
	"\x13client_send_time_ms\x18\x02 \x01(\x03R\x10clientSendTimeMs\"\xc4\x01\n" +
	"\x10TimeSyncResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12-\n" +
	"\x13client_send_time_ms\x18\x02 \x01(\x03R\x10clientSendTimeMs\x123\n" +
	"\x16server_receive_time_ms\x18\x03 \x01(\x03R\x13serverReceiveTimeMs\x12-\n" +
	"\x13server_send_time_ms\x18\x04 \x01(\x03R\x10serverSendTimeMs\"\x96\x01\n" +
	"\rRoutingUpdate\x12$\n" +
	"\x0eorigin_node_id\x18\x01 \x01(\x03R\foriginNodeId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x12?\n" +
	"\x06routes\x18\x03 \x03(\v2'.notifier.cluster.v1.RouteAdvertisementR\x06routes\"\xde\x01\n" +
	"\x12RouteAdvertisement\x12.\n" +
	"\x13destination_node_id\x18\x01 \x01(\x03R\x11destinationNodeId\x12\x1c\n" +
	"\treachable\x18\x02 \x01(\bR\treachable\x12\"\n" +
	"\rtotal_cost_ms\x18\x03 \x01(\rR\vtotalCostMs\x12(\n" +
	"\x10residual_cost_ms\x18\x04 \x01(\rR\x0eresidualCostMs\x12,\n" +
	"\x12residual_jitter_ms\x18\x05 \x01(\rR\x10residualJitterMs\"\xf8\x02\n" +
	"\x0fTransientPacket\x12\x1b\n" +
	"\tpacket_id\x18\x01 \x01(\x04R\bpacketId\x12$\n" +
	"\x0esource_node_id\x18\x02 \x01(\x03R\fsourceNodeId\x12$\n" +
	"\x0etarget_node_id\x18\x03 \x01(\x03R\ftargetNodeId\x12A\n" +
	"\trecipient\x18\x04 \x01(\v2#.notifier.cluster.v1.ClusterUserRefR\trecipient\x12;\n" +
	"\x06sender\x18\x06 \x01(\v2#.notifier.cluster.v1.ClusterUserRefR\x06sender\x12\x12\n" +
	"\x04body\x18\a \x01(\fR\x04body\x12M\n" +
	"\rdelivery_mode\x18\b \x01(\x0e2(.notifier.cluster.v1.ClusterDeliveryModeR\fdeliveryMode\x12\x19\n" +
	"\bttl_hops\x18\t \x01(\rR\attlHops*\xb4\x01\n" +
	"\x15SnapshotPartitionKind\x12'\n" +
	"#SNAPSHOT_PARTITION_KIND_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dSNAPSHOT_PARTITION_KIND_USERS\x10\x01\x12$\n" +
	" SNAPSHOT_PARTITION_KIND_MESSAGES\x10\x02\x12)\n" +
	"%SNAPSHOT_PARTITION_KIND_SUBSCRIPTIONS\x10\x03*\x8a\x01\n" +
	"\x13ClusterDeliveryMode\x12%\n" +
	"!CLUSTER_DELIVERY_MODE_UNSPECIFIED\x10\x00\x12%\n" +
	"!CLUSTER_DELIVERY_MODE_BEST_EFFORT\x10\x01\x12%\n" +
	"!CLUSTER_DELIVERY_MODE_ROUTE_RETRY\x10\x02B/Z-github.com/tursom/turntf/internal/proto;protob\x06proto3"

var (
	file_cluster_proto_rawDescOnce sync.Once
	file_cluster_proto_rawDescData []byte
)

func file_cluster_proto_rawDescGZIP() []byte {
	file_cluster_proto_rawDescOnce.Do(func() {
		file_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_proto_rawDesc), len(file_cluster_proto_rawDesc)))
	})
	return file_cluster_proto_rawDescData
}

var file_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_cluster_proto_goTypes = []any{
	(SnapshotPartitionKind)(0),       // 0: notifier.cluster.v1.SnapshotPartitionKind
	(ClusterDeliveryMode)(0),         // 1: notifier.cluster.v1.ClusterDeliveryMode
	(*Envelope)(nil),                 // 2: notifier.cluster.v1.Envelope
	(*Hello)(nil),                    // 3: notifier.cluster.v1.Hello
	(*OriginProgress)(nil),           // 4: notifier.cluster.v1.OriginProgress
	(*Ack)(nil),                      // 5: notifier.cluster.v1.Ack
	(*EventBatch)(nil),               // 6: notifier.cluster.v1.EventBatch
	(*ReplicatedEvent)(nil),          // 7: notifier.cluster.v1.ReplicatedEvent
	(*UserCreatedEvent)(nil),         // 8: notifier.cluster.v1.UserCreatedEvent
	(*UserUpdatedEvent)(nil),         // 9: notifier.cluster.v1.UserUpdatedEvent
	(*UserDeletedEvent)(nil),         // 10: notifier.cluster.v1.UserDeletedEvent
	(*ClusterUserRef)(nil),           // 11: notifier.cluster.v1.ClusterUserRef
	(*MessageCreatedEvent)(nil),      // 12: notifier.cluster.v1.MessageCreatedEvent
	(*ChannelSubscribedEvent)(nil),   // 13: notifier.cluster.v1.ChannelSubscribedEvent
	(*ChannelUnsubscribedEvent)(nil), // 14: notifier.cluster.v1.ChannelUnsubscribedEvent
	(*PullEvents)(nil),               // 15: notifier.cluster.v1.PullEvents
	(*SnapshotDigest)(nil),           // 16: notifier.cluster.v1.SnapshotDigest
	(*SnapshotChunk)(nil),            // 17: notifier.cluster.v1.SnapshotChunk
	(*SnapshotPartitionDigest)(nil),  // 18: notifier.cluster.v1.SnapshotPartitionDigest
	(*SnapshotRow)(nil),              // 19: notifier.cluster.v1.SnapshotRow
	(*SnapshotUserRow)(nil),          // 20: notifier.cluster.v1.SnapshotUserRow
	(*SnapshotTombstoneRow)(nil),     // 21: notifier.cluster.v1.SnapshotTombstoneRow
	(*SnapshotMessageRow)(nil),       // 22: notifier.cluster.v1.SnapshotMessageRow
	(*SnapshotSubscriptionRow)(nil),  // 23: notifier.cluster.v1.SnapshotSubscriptionRow
	(*TimeSyncRequest)(nil),          // 24: notifier.cluster.v1.TimeSyncRequest
	(*TimeSyncResponse)(nil),         // 25: notifier.cluster.v1.TimeSyncResponse
	(*RoutingUpdate)(nil),            // 26: notifier.cluster.v1.RoutingUpdate
	(*RouteAdvertisement)(nil),       // 27: notifier.cluster.v1.RouteAdvertisement
	(*TransientPacket)(nil),          // 28: notifier.cluster.v1.TransientPacket
}
var file_cluster_proto_depIdxs = []int32{
	3,  // 0: notifier.cluster.v1.Envelope.hello:type_name -> notifier.cluster.v1.Hello
	5,  // 1: notifier.cluster.v1.Envelope.ack:type_name -> notifier.cluster.v1.Ack
	6,  // 2: notifier.cluster.v1.Envelope.event_batch:type_name -> notifier.cluster.v1.EventBatch
	15, // 3: notifier.cluster.v1.Envelope.pull_events:type_name -> notifier.cluster.v1.PullEvents
	16, // 4: notifier.cluster.v1.Envelope.snapshot_digest:type_name -> notifier.cluster.v1.SnapshotDigest
	17, // 5: notifier.cluster.v1.Envelope.snapshot_chunk:type_name -> notifier.cluster.v1.SnapshotChunk
	24, // 6: notifier.cluster.v1.Envelope.time_sync_request:type_name -> notifier.cluster.v1.TimeSyncRequest
	25, // 7: notifier.cluster.v1.Envelope.time_sync_response:type_name -> notifier.cluster.v1.TimeSyncResponse
	26, // 8: notifier.cluster.v1.Envelope.routing_update:type_name -> notifier.cluster.v1.RoutingUpdate
	28, // 9: notifier.cluster.v1.Envelope.transient_packet:type_name -> notifier.cluster.v1.TransientPacket
	4,  // 10: notifier.cluster.v1.Hello.origin_progress:type_name -> notifier.cluster.v1.OriginProgress
	7,  // 11: notifier.cluster.v1.EventBatch.events:type_name -> notifier.cluster.v1.ReplicatedEvent
	8,  // 12: notifier.cluster.v1.ReplicatedEvent.user_created:type_name -> notifier.cluster.v1.UserCreatedEvent
	9,  // 13: notifier.cluster.v1.ReplicatedEvent.user_updated:type_name -> notifier.cluster.v1.UserUpdatedEvent
	10, // 14: notifier.cluster.v1.ReplicatedEvent.user_deleted:type_name -> notifier.cluster.v1.UserDeletedEvent
	12, // 15: notifier.cluster.v1.ReplicatedEvent.message_created:type_name -> notifier.cluster.v1.MessageCreatedEvent
	13, // 16: notifier.cluster.v1.ReplicatedEvent.channel_subscribed:type_name -> notifier.cluster.v1.ChannelSubscribedEvent
	14, // 17: notifier.cluster.v1.ReplicatedEvent.channel_unsubscribed:type_name -> notifier.cluster.v1.ChannelUnsubscribedEvent
	11, // 18: notifier.cluster.v1.MessageCreatedEvent.recipient:type_name -> notifier.cluster.v1.ClusterUserRef
	11, // 19: notifier.cluster.v1.MessageCreatedEvent.sender:type_name -> notifier.cluster.v1.ClusterUserRef
	11, // 20: notifier.cluster.v1.ChannelSubscribedEvent.subscriber:type_name -> notifier.cluster.v1.ClusterUserRef
	11, // 21: notifier.cluster.v1.ChannelSubscribedEvent.channel:type_name -> notifier.cluster.v1.ClusterUserRef
	11, // 22: notifier.cluster.v1.ChannelUnsubscribedEvent.subscriber:type_name -> notifier.cluster.v1.ClusterUserRef
	11, // 23: notifier.cluster.v1.ChannelUnsubscribedEvent.channel:type_name -> notifier.cluster.v1.ClusterUserRef
	18, // 24: notifier.cluster.v1.SnapshotDigest.partitions:type_name -> notifier.cluster.v1.SnapshotPartitionDigest
	19, // 25: notifier.cluster.v1.SnapshotChunk.rows:type_name -> notifier.cluster.v1.SnapshotRow
	0,  // 26: notifier.cluster.v1.SnapshotChunk.kind:type_name -> notifier.cluster.v1.SnapshotPartitionKind
	0,  // 27: notifier.cluster.v1.SnapshotPartitionDigest.kind:type_name -> notifier.cluster.v1.SnapshotPartitionKind
	20, // 28: notifier.cluster.v1.SnapshotRow.user:type_name -> notifier.cluster.v1.SnapshotUserRow
	21, // 29: notifier.cluster.v1.SnapshotRow.tombstone:type_name -> notifier.cluster.v1.SnapshotTombstoneRow
	22, // 30: notifier.cluster.v1.SnapshotRow.message:type_name -> notifier.cluster.v1.SnapshotMessageRow
	23, // 31: notifier.cluster.v1.SnapshotRow.subscription:type_name -> notifier.cluster.v1.SnapshotSubscriptionRow
	11, // 32: notifier.cluster.v1.SnapshotMessageRow.recipient:type_name -> notifier.cluster.v1.ClusterUserRef
	11, // 33: notifier.cluster.v1.SnapshotMessageRow.sender:type_name -> notifier.cluster.v1.ClusterUserRef
	11, // 34: notifier.cluster.v1.SnapshotSubscriptionRow.subscriber:type_name -> notifier.cluster.v1.ClusterUserRef
	11, // 35: notifier.cluster.v1.SnapshotSubscriptionRow.channel:type_name -> notifier.cluster.v1.ClusterUserRef
	27, // 36: notifier.cluster.v1.RoutingUpdate.routes:type_name -> notifier.cluster.v1.RouteAdvertisement
	11, // 37: notifier.cluster.v1.TransientPacket.recipient:type_name -> notifier.cluster.v1.ClusterUserRef
	11, // 38: notifier.cluster.v1.TransientPacket.sender:type_name -> notifier.cluster.v1.ClusterUserRef
	1,  // 39: notifier.cluster.v1.TransientPacket.delivery_mode:type_name -> notifier.cluster.v1.ClusterDeliveryMode
	40, // [40:40] is the sub-list for method output_type
	40, // [40:40] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_cluster_proto_init() }
func file_cluster_proto_init() {
	if File_cluster_proto != nil {
		return
	}
	file_cluster_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Hello)(nil),
		(*Envelope_Ack)(nil),
		(*Envelope_EventBatch)(nil),
		(*Envelope_PullEvents)(nil),
		(*Envelope_SnapshotDigest)(nil),
		(*Envelope_SnapshotChunk)(nil),
		(*Envelope_TimeSyncRequest)(nil),
		(*Envelope_TimeSyncResponse)(nil),
		(*Envelope_RoutingUpdate)(nil),
		(*Envelope_TransientPacket)(nil),
	}
	file_cluster_proto_msgTypes[5].OneofWrappers = []any{
		(*ReplicatedEvent_UserCreated)(nil),
		(*ReplicatedEvent_UserUpdated)(nil),
		(*ReplicatedEvent_UserDeleted)(nil),
		(*ReplicatedEvent_MessageCreated)(nil),
		(*ReplicatedEvent_ChannelSubscribed)(nil),
		(*ReplicatedEvent_ChannelUnsubscribed)(nil),
	}
	file_cluster_proto_msgTypes[17].OneofWrappers = []any{
		(*SnapshotRow_User)(nil),
		(*SnapshotRow_Tombstone)(nil),
		(*SnapshotRow_Message)(nil),
		(*SnapshotRow_Subscription)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_proto_rawDesc), len(file_cluster_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cluster_proto_goTypes,
		DependencyIndexes: file_cluster_proto_depIdxs,
		EnumInfos:         file_cluster_proto_enumTypes,
		MessageInfos:      file_cluster_proto_msgTypes,
	}.Build()
	File_cluster_proto = out.File
	file_cluster_proto_goTypes = nil
	file_cluster_proto_depIdxs = nil
}
