// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/cluster.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	NodeId    string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Sequence  uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SentAtHlc string                 `protobuf:"bytes,3,opt,name=sent_at_hlc,json=sentAtHlc,proto3" json:"sent_at_hlc,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Envelope_Hello
	//	*Envelope_Ack
	//	*Envelope_EventBatch
	//	*Envelope_PullEvents
	//	*Envelope_SnapshotDigest
	//	*Envelope_SnapshotChunk
	//	*Envelope_TimeSyncRequest
	//	*Envelope_TimeSyncResponse
	Body          isEnvelope_Body `protobuf_oneof:"body"`
	Hmac          []byte          `protobuf:"bytes,12,opt,name=hmac,proto3" json:"hmac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Envelope) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Envelope) GetSentAtHlc() string {
	if x != nil {
		return x.SentAtHlc
	}
	return ""
}

func (x *Envelope) GetBody() isEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Envelope) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Envelope) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *Envelope) GetEventBatch() *EventBatch {
	if x != nil {
		if x, ok := x.Body.(*Envelope_EventBatch); ok {
			return x.EventBatch
		}
	}
	return nil
}

func (x *Envelope) GetPullEvents() *PullEvents {
	if x != nil {
		if x, ok := x.Body.(*Envelope_PullEvents); ok {
			return x.PullEvents
		}
	}
	return nil
}

func (x *Envelope) GetSnapshotDigest() *SnapshotDigest {
	if x != nil {
		if x, ok := x.Body.(*Envelope_SnapshotDigest); ok {
			return x.SnapshotDigest
		}
	}
	return nil
}

func (x *Envelope) GetSnapshotChunk() *SnapshotChunk {
	if x != nil {
		if x, ok := x.Body.(*Envelope_SnapshotChunk); ok {
			return x.SnapshotChunk
		}
	}
	return nil
}

func (x *Envelope) GetTimeSyncRequest() *TimeSyncRequest {
	if x != nil {
		if x, ok := x.Body.(*Envelope_TimeSyncRequest); ok {
			return x.TimeSyncRequest
		}
	}
	return nil
}

func (x *Envelope) GetTimeSyncResponse() *TimeSyncResponse {
	if x != nil {
		if x, ok := x.Body.(*Envelope_TimeSyncResponse); ok {
			return x.TimeSyncResponse
		}
	}
	return nil
}

func (x *Envelope) GetHmac() []byte {
	if x != nil {
		return x.Hmac
	}
	return nil
}

type isEnvelope_Body interface {
	isEnvelope_Body()
}

type Envelope_Hello struct {
	Hello *Hello `protobuf:"bytes,4,opt,name=hello,proto3,oneof"`
}

type Envelope_Ack struct {
	Ack *Ack `protobuf:"bytes,5,opt,name=ack,proto3,oneof"`
}

type Envelope_EventBatch struct {
	EventBatch *EventBatch `protobuf:"bytes,6,opt,name=event_batch,json=eventBatch,proto3,oneof"`
}

type Envelope_PullEvents struct {
	PullEvents *PullEvents `protobuf:"bytes,7,opt,name=pull_events,json=pullEvents,proto3,oneof"`
}

type Envelope_SnapshotDigest struct {
	SnapshotDigest *SnapshotDigest `protobuf:"bytes,8,opt,name=snapshot_digest,json=snapshotDigest,proto3,oneof"`
}

type Envelope_SnapshotChunk struct {
	SnapshotChunk *SnapshotChunk `protobuf:"bytes,9,opt,name=snapshot_chunk,json=snapshotChunk,proto3,oneof"`
}

type Envelope_TimeSyncRequest struct {
	TimeSyncRequest *TimeSyncRequest `protobuf:"bytes,10,opt,name=time_sync_request,json=timeSyncRequest,proto3,oneof"`
}

type Envelope_TimeSyncResponse struct {
	TimeSyncResponse *TimeSyncResponse `protobuf:"bytes,11,opt,name=time_sync_response,json=timeSyncResponse,proto3,oneof"`
}

func (*Envelope_Hello) isEnvelope_Body() {}

func (*Envelope_Ack) isEnvelope_Body() {}

func (*Envelope_EventBatch) isEnvelope_Body() {}

func (*Envelope_PullEvents) isEnvelope_Body() {}

func (*Envelope_SnapshotDigest) isEnvelope_Body() {}

func (*Envelope_SnapshotChunk) isEnvelope_Body() {}

func (*Envelope_TimeSyncRequest) isEnvelope_Body() {}

func (*Envelope_TimeSyncResponse) isEnvelope_Body() {}

type Hello struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AdvertiseAddr     string                 `protobuf:"bytes,2,opt,name=advertise_addr,json=advertiseAddr,proto3" json:"advertise_addr,omitempty"`
	ProtocolVersion   string                 `protobuf:"bytes,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	LastSequence      uint64                 `protobuf:"varint,4,opt,name=last_sequence,json=lastSequence,proto3" json:"last_sequence,omitempty"`
	SnapshotVersion   string                 `protobuf:"bytes,5,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	MessageWindowSize uint32                 `protobuf:"varint,6,opt,name=message_window_size,json=messageWindowSize,proto3" json:"message_window_size,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_proto_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Hello) GetAdvertiseAddr() string {
	if x != nil {
		return x.AdvertiseAddr
	}
	return ""
}

func (x *Hello) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *Hello) GetLastSequence() uint64 {
	if x != nil {
		return x.LastSequence
	}
	return 0
}

func (x *Hello) GetSnapshotVersion() string {
	if x != nil {
		return x.SnapshotVersion
	}
	return ""
}

func (x *Hello) GetMessageWindowSize() uint32 {
	if x != nil {
		return x.MessageWindowSize
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AckedSequence uint64                 `protobuf:"varint,2,opt,name=acked_sequence,json=ackedSequence,proto3" json:"acked_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *Ack) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Ack) GetAckedSequence() uint64 {
	if x != nil {
		return x.AckedSequence
	}
	return 0
}

type EventBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*ReplicatedEvent     `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBatch) Reset() {
	*x = EventBatch{}
	mi := &file_proto_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBatch) ProtoMessage() {}

func (x *EventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBatch.ProtoReflect.Descriptor instead.
func (*EventBatch) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *EventBatch) GetEvents() []*ReplicatedEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ReplicatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	AggregateType string                 `protobuf:"bytes,3,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	AggregateId   int64                  `protobuf:"varint,4,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	Hlc           string                 `protobuf:"bytes,5,opt,name=hlc,proto3" json:"hlc,omitempty"`
	OriginNodeId  string                 `protobuf:"bytes,6,opt,name=origin_node_id,json=originNodeId,proto3" json:"origin_node_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicatedEvent) Reset() {
	*x = ReplicatedEvent{}
	mi := &file_proto_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicatedEvent) ProtoMessage() {}

func (x *ReplicatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicatedEvent.ProtoReflect.Descriptor instead.
func (*ReplicatedEvent) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *ReplicatedEvent) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *ReplicatedEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ReplicatedEvent) GetAggregateType() string {
	if x != nil {
		return x.AggregateType
	}
	return ""
}

func (x *ReplicatedEvent) GetAggregateId() int64 {
	if x != nil {
		return x.AggregateId
	}
	return 0
}

func (x *ReplicatedEvent) GetHlc() string {
	if x != nil {
		return x.Hlc
	}
	return ""
}

func (x *ReplicatedEvent) GetOriginNodeId() string {
	if x != nil {
		return x.OriginNodeId
	}
	return ""
}

func (x *ReplicatedEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PullEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AfterSequence uint64                 `protobuf:"varint,1,opt,name=after_sequence,json=afterSequence,proto3" json:"after_sequence,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullEvents) Reset() {
	*x = PullEvents{}
	mi := &file_proto_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullEvents) ProtoMessage() {}

func (x *PullEvents) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullEvents.ProtoReflect.Descriptor instead.
func (*PullEvents) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *PullEvents) GetAfterSequence() uint64 {
	if x != nil {
		return x.AfterSequence
	}
	return 0
}

func (x *PullEvents) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SnapshotDigest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SnapshotVersion string                 `protobuf:"bytes,1,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	Partitions      [][]byte               `protobuf:"bytes,2,rep,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SnapshotDigest) Reset() {
	*x = SnapshotDigest{}
	mi := &file_proto_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotDigest) ProtoMessage() {}

func (x *SnapshotDigest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotDigest.ProtoReflect.Descriptor instead.
func (*SnapshotDigest) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *SnapshotDigest) GetSnapshotVersion() string {
	if x != nil {
		return x.SnapshotVersion
	}
	return ""
}

func (x *SnapshotDigest) GetPartitions() [][]byte {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type SnapshotChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     string                 `protobuf:"bytes,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Rows          [][]byte               `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotChunk) Reset() {
	*x = SnapshotChunk{}
	mi := &file_proto_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotChunk) ProtoMessage() {}

func (x *SnapshotChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotChunk.ProtoReflect.Descriptor instead.
func (*SnapshotChunk) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *SnapshotChunk) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *SnapshotChunk) GetRows() [][]byte {
	if x != nil {
		return x.Rows
	}
	return nil
}

type TimeSyncRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ClientSendTimeMs int64                  `protobuf:"varint,2,opt,name=client_send_time_ms,json=clientSendTimeMs,proto3" json:"client_send_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TimeSyncRequest) Reset() {
	*x = TimeSyncRequest{}
	mi := &file_proto_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSyncRequest) ProtoMessage() {}

func (x *TimeSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSyncRequest.ProtoReflect.Descriptor instead.
func (*TimeSyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{8}
}

func (x *TimeSyncRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *TimeSyncRequest) GetClientSendTimeMs() int64 {
	if x != nil {
		return x.ClientSendTimeMs
	}
	return 0
}

type TimeSyncResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RequestId           uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ClientSendTimeMs    int64                  `protobuf:"varint,2,opt,name=client_send_time_ms,json=clientSendTimeMs,proto3" json:"client_send_time_ms,omitempty"`
	ServerReceiveTimeMs int64                  `protobuf:"varint,3,opt,name=server_receive_time_ms,json=serverReceiveTimeMs,proto3" json:"server_receive_time_ms,omitempty"`
	ServerSendTimeMs    int64                  `protobuf:"varint,4,opt,name=server_send_time_ms,json=serverSendTimeMs,proto3" json:"server_send_time_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TimeSyncResponse) Reset() {
	*x = TimeSyncResponse{}
	mi := &file_proto_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSyncResponse) ProtoMessage() {}

func (x *TimeSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSyncResponse.ProtoReflect.Descriptor instead.
func (*TimeSyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{9}
}

func (x *TimeSyncResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *TimeSyncResponse) GetClientSendTimeMs() int64 {
	if x != nil {
		return x.ClientSendTimeMs
	}
	return 0
}

func (x *TimeSyncResponse) GetServerReceiveTimeMs() int64 {
	if x != nil {
		return x.ServerReceiveTimeMs
	}
	return 0
}

func (x *TimeSyncResponse) GetServerSendTimeMs() int64 {
	if x != nil {
		return x.ServerSendTimeMs
	}
	return 0
}

type UserEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Hlc           string                 `protobuf:"bytes,4,opt,name=hlc,proto3" json:"hlc,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserEvent) Reset() {
	*x = UserEvent{}
	mi := &file_proto_cluster_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEvent) ProtoMessage() {}

func (x *UserEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEvent.ProtoReflect.Descriptor instead.
func (*UserEvent) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{10}
}

func (x *UserEvent) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *UserEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *UserEvent) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserEvent) GetHlc() string {
	if x != nil {
		return x.Hlc
	}
	return ""
}

func (x *UserEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type MessageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	MessageId     int64                  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Hlc           string                 `protobuf:"bytes,5,opt,name=hlc,proto3" json:"hlc,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageEvent) Reset() {
	*x = MessageEvent{}
	mi := &file_proto_cluster_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEvent) ProtoMessage() {}

func (x *MessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEvent.ProtoReflect.Descriptor instead.
func (*MessageEvent) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{11}
}

func (x *MessageEvent) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *MessageEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *MessageEvent) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *MessageEvent) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MessageEvent) GetHlc() string {
	if x != nil {
		return x.Hlc
	}
	return ""
}

func (x *MessageEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_proto_cluster_proto protoreflect.FileDescriptor

const file_proto_cluster_proto_rawDesc = "" +
	"\n" +
	"\x13proto/cluster.proto\x12\x13notifier.cluster.v1\"\xad\x05\n" +
	"\bEnvelope\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x1e\n" +
	"\vsent_at_hlc\x18\x03 \x01(\tR\tsentAtHlc\x122\n" +
	"\x05hello\x18\x04 \x01(\v2\x1a.notifier.cluster.v1.HelloH\x00R\x05hello\x12,\n" +
	"\x03ack\x18\x05 \x01(\v2\x18.notifier.cluster.v1.AckH\x00R\x03ack\x12B\n" +
	"\vevent_batch\x18\x06 \x01(\v2\x1f.notifier.cluster.v1.EventBatchH\x00R\n" +
	"eventBatch\x12B\n" +
	"\vpull_events\x18\a \x01(\v2\x1f.notifier.cluster.v1.PullEventsH\x00R\n" +
	"pullEvents\x12N\n" +
	"\x0fsnapshot_digest\x18\b \x01(\v2#.notifier.cluster.v1.SnapshotDigestH\x00R\x0esnapshotDigest\x12K\n" +
	"\x0esnapshot_chunk\x18\t \x01(\v2\".notifier.cluster.v1.SnapshotChunkH\x00R\rsnapshotChunk\x12R\n" +
	"\x11time_sync_request\x18\n" +
	" \x01(\v2$.notifier.cluster.v1.TimeSyncRequestH\x00R\x0ftimeSyncRequest\x12U\n" +
	"\x12time_sync_response\x18\v \x01(\v2%.notifier.cluster.v1.TimeSyncResponseH\x00R\x10timeSyncResponse\x12\x12\n" +
	"\x04hmac\x18\f \x01(\fR\x04hmacB\x06\n" +
	"\x04body\"\xf2\x01\n" +
	"\x05Hello\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12%\n" +
	"\x0eadvertise_addr\x18\x02 \x01(\tR\radvertiseAddr\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\tR\x0fprotocolVersion\x12#\n" +
	"\rlast_sequence\x18\x04 \x01(\x04R\flastSequence\x12)\n" +
	"\x10snapshot_version\x18\x05 \x01(\tR\x0fsnapshotVersion\x12.\n" +
	"\x13message_window_size\x18\x06 \x01(\rR\x11messageWindowSize\"E\n" +
	"\x03Ack\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12%\n" +
	"\x0eacked_sequence\x18\x02 \x01(\x04R\rackedSequence\"J\n" +
	"\n" +
	"EventBatch\x12<\n" +
	"\x06events\x18\x01 \x03(\v2$.notifier.cluster.v1.ReplicatedEventR\x06events\"\xdc\x01\n" +
	"\x0fReplicatedEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12%\n" +
	"\x0eaggregate_type\x18\x03 \x01(\tR\raggregateType\x12!\n" +
	"\faggregate_id\x18\x04 \x01(\x03R\vaggregateId\x12\x10\n" +
	"\x03hlc\x18\x05 \x01(\tR\x03hlc\x12$\n" +
	"\x0eorigin_node_id\x18\x06 \x01(\tR\foriginNodeId\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\"I\n" +
	"\n" +
	"PullEvents\x12%\n" +
	"\x0eafter_sequence\x18\x01 \x01(\x04R\rafterSequence\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"[\n" +
	"\x0eSnapshotDigest\x12)\n" +
	"\x10snapshot_version\x18\x01 \x01(\tR\x0fsnapshotVersion\x12\x1e\n" +
	"\n" +
	"partitions\x18\x02 \x03(\fR\n" +
	"partitions\"A\n" +
	"\rSnapshotChunk\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\tR\tpartition\x12\x12\n" +
	"\x04rows\x18\x02 \x03(\fR\x04rows\"_\n" +
	"\x0fTimeSyncRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12-\n" +
	"\x13client_send_time_ms\x18\x02 \x01(\x03R\x10clientSendTimeMs\"\xc4\x01\n" +
	"\x10TimeSyncResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12-\n" +
	"\x13client_send_time_ms\x18\x02 \x01(\x03R\x10clientSendTimeMs\x123\n" +
	"\x16server_receive_time_ms\x18\x03 \x01(\x03R\x13serverReceiveTimeMs\x12-\n" +
	"\x13server_send_time_ms\x18\x04 \x01(\x03R\x10serverSendTimeMs\"\x7f\n" +
	"\tUserEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x10\n" +
	"\x03hlc\x18\x04 \x01(\tR\x03hlc\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"\xa1\x01\n" +
	"\fMessageEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x10\n" +
	"\x03hlc\x18\x05 \x01(\tR\x03hlc\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayloadB\x1fZ\x1dnotifier/internal/proto;protob\x06proto3"

var (
	file_proto_cluster_proto_rawDescOnce sync.Once
	file_proto_cluster_proto_rawDescData []byte
)

func file_proto_cluster_proto_rawDescGZIP() []byte {
	file_proto_cluster_proto_rawDescOnce.Do(func() {
		file_proto_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cluster_proto_rawDesc), len(file_proto_cluster_proto_rawDesc)))
	})
	return file_proto_cluster_proto_rawDescData
}

var file_proto_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_cluster_proto_goTypes = []any{
	(*Envelope)(nil),         // 0: notifier.cluster.v1.Envelope
	(*Hello)(nil),            // 1: notifier.cluster.v1.Hello
	(*Ack)(nil),              // 2: notifier.cluster.v1.Ack
	(*EventBatch)(nil),       // 3: notifier.cluster.v1.EventBatch
	(*ReplicatedEvent)(nil),  // 4: notifier.cluster.v1.ReplicatedEvent
	(*PullEvents)(nil),       // 5: notifier.cluster.v1.PullEvents
	(*SnapshotDigest)(nil),   // 6: notifier.cluster.v1.SnapshotDigest
	(*SnapshotChunk)(nil),    // 7: notifier.cluster.v1.SnapshotChunk
	(*TimeSyncRequest)(nil),  // 8: notifier.cluster.v1.TimeSyncRequest
	(*TimeSyncResponse)(nil), // 9: notifier.cluster.v1.TimeSyncResponse
	(*UserEvent)(nil),        // 10: notifier.cluster.v1.UserEvent
	(*MessageEvent)(nil),     // 11: notifier.cluster.v1.MessageEvent
}
var file_proto_cluster_proto_depIdxs = []int32{
	1, // 0: notifier.cluster.v1.Envelope.hello:type_name -> notifier.cluster.v1.Hello
	2, // 1: notifier.cluster.v1.Envelope.ack:type_name -> notifier.cluster.v1.Ack
	3, // 2: notifier.cluster.v1.Envelope.event_batch:type_name -> notifier.cluster.v1.EventBatch
	5, // 3: notifier.cluster.v1.Envelope.pull_events:type_name -> notifier.cluster.v1.PullEvents
	6, // 4: notifier.cluster.v1.Envelope.snapshot_digest:type_name -> notifier.cluster.v1.SnapshotDigest
	7, // 5: notifier.cluster.v1.Envelope.snapshot_chunk:type_name -> notifier.cluster.v1.SnapshotChunk
	8, // 6: notifier.cluster.v1.Envelope.time_sync_request:type_name -> notifier.cluster.v1.TimeSyncRequest
	9, // 7: notifier.cluster.v1.Envelope.time_sync_response:type_name -> notifier.cluster.v1.TimeSyncResponse
	4, // 8: notifier.cluster.v1.EventBatch.events:type_name -> notifier.cluster.v1.ReplicatedEvent
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_proto_cluster_proto_init() }
func file_proto_cluster_proto_init() {
	if File_proto_cluster_proto != nil {
		return
	}
	file_proto_cluster_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Hello)(nil),
		(*Envelope_Ack)(nil),
		(*Envelope_EventBatch)(nil),
		(*Envelope_PullEvents)(nil),
		(*Envelope_SnapshotDigest)(nil),
		(*Envelope_SnapshotChunk)(nil),
		(*Envelope_TimeSyncRequest)(nil),
		(*Envelope_TimeSyncResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cluster_proto_rawDesc), len(file_proto_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_cluster_proto_goTypes,
		DependencyIndexes: file_proto_cluster_proto_depIdxs,
		MessageInfos:      file_proto_cluster_proto_msgTypes,
	}.Build()
	File_proto_cluster_proto = out.File
	file_proto_cluster_proto_goTypes = nil
	file_proto_cluster_proto_depIdxs = nil
}
