// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: mesh.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransportKind int32

const (
	TransportKind_TRANSPORT_KIND_UNSPECIFIED TransportKind = 0
	TransportKind_TRANSPORT_KIND_LIBP2P      TransportKind = 1
	TransportKind_TRANSPORT_KIND_ZEROMQ      TransportKind = 2
)

// Enum value maps for TransportKind.
var (
	TransportKind_name = map[int32]string{
		0: "TRANSPORT_KIND_UNSPECIFIED",
		1: "TRANSPORT_KIND_LIBP2P",
		2: "TRANSPORT_KIND_ZEROMQ",
	}
	TransportKind_value = map[string]int32{
		"TRANSPORT_KIND_UNSPECIFIED": 0,
		"TRANSPORT_KIND_LIBP2P":      1,
		"TRANSPORT_KIND_ZEROMQ":      2,
	}
)

func (x TransportKind) Enum() *TransportKind {
	p := new(TransportKind)
	*p = x
	return p
}

func (x TransportKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportKind) Descriptor() protoreflect.EnumDescriptor {
	return file_mesh_proto_enumTypes[0].Descriptor()
}

func (TransportKind) Type() protoreflect.EnumType {
	return &file_mesh_proto_enumTypes[0]
}

func (x TransportKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransportKind.Descriptor instead.
func (TransportKind) EnumDescriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{0}
}

type TrafficClass int32

const (
	TrafficClass_TRAFFIC_CLASS_UNSPECIFIED     TrafficClass = 0
	TrafficClass_TRAFFIC_CONTROL_CRITICAL      TrafficClass = 1
	TrafficClass_TRAFFIC_CONTROL_QUERY         TrafficClass = 2
	TrafficClass_TRAFFIC_TRANSIENT_INTERACTIVE TrafficClass = 3
	TrafficClass_TRAFFIC_REPLICATION_STREAM    TrafficClass = 4
	TrafficClass_TRAFFIC_SNAPSHOT_BULK         TrafficClass = 5
)

// Enum value maps for TrafficClass.
var (
	TrafficClass_name = map[int32]string{
		0: "TRAFFIC_CLASS_UNSPECIFIED",
		1: "TRAFFIC_CONTROL_CRITICAL",
		2: "TRAFFIC_CONTROL_QUERY",
		3: "TRAFFIC_TRANSIENT_INTERACTIVE",
		4: "TRAFFIC_REPLICATION_STREAM",
		5: "TRAFFIC_SNAPSHOT_BULK",
	}
	TrafficClass_value = map[string]int32{
		"TRAFFIC_CLASS_UNSPECIFIED":     0,
		"TRAFFIC_CONTROL_CRITICAL":      1,
		"TRAFFIC_CONTROL_QUERY":         2,
		"TRAFFIC_TRANSIENT_INTERACTIVE": 3,
		"TRAFFIC_REPLICATION_STREAM":    4,
		"TRAFFIC_SNAPSHOT_BULK":         5,
	}
)

func (x TrafficClass) Enum() *TrafficClass {
	p := new(TrafficClass)
	*p = x
	return p
}

func (x TrafficClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrafficClass) Descriptor() protoreflect.EnumDescriptor {
	return file_mesh_proto_enumTypes[1].Descriptor()
}

func (TrafficClass) Type() protoreflect.EnumType {
	return &file_mesh_proto_enumTypes[1]
}

func (x TrafficClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrafficClass.Descriptor instead.
func (TrafficClass) EnumDescriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{1}
}

type ForwardingDisposition int32

const (
	ForwardingDisposition_FORWARDING_DISPOSITION_UNSPECIFIED ForwardingDisposition = 0
	ForwardingDisposition_FORWARDING_DISPOSITION_ALLOW       ForwardingDisposition = 1
	ForwardingDisposition_FORWARDING_DISPOSITION_DISCOURAGE  ForwardingDisposition = 2
	ForwardingDisposition_FORWARDING_DISPOSITION_DENY        ForwardingDisposition = 3
)

// Enum value maps for ForwardingDisposition.
var (
	ForwardingDisposition_name = map[int32]string{
		0: "FORWARDING_DISPOSITION_UNSPECIFIED",
		1: "FORWARDING_DISPOSITION_ALLOW",
		2: "FORWARDING_DISPOSITION_DISCOURAGE",
		3: "FORWARDING_DISPOSITION_DENY",
	}
	ForwardingDisposition_value = map[string]int32{
		"FORWARDING_DISPOSITION_UNSPECIFIED": 0,
		"FORWARDING_DISPOSITION_ALLOW":       1,
		"FORWARDING_DISPOSITION_DISCOURAGE":  2,
		"FORWARDING_DISPOSITION_DENY":        3,
	}
)

func (x ForwardingDisposition) Enum() *ForwardingDisposition {
	p := new(ForwardingDisposition)
	*p = x
	return p
}

func (x ForwardingDisposition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ForwardingDisposition) Descriptor() protoreflect.EnumDescriptor {
	return file_mesh_proto_enumTypes[2].Descriptor()
}

func (ForwardingDisposition) Type() protoreflect.EnumType {
	return &file_mesh_proto_enumTypes[2]
}

func (x ForwardingDisposition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ForwardingDisposition.Descriptor instead.
func (ForwardingDisposition) EnumDescriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{2}
}

type PathClass int32

const (
	PathClass_PATH_CLASS_UNSPECIFIED            PathClass = 0
	PathClass_PATH_CLASS_DIRECT                 PathClass = 1
	PathClass_PATH_CLASS_SAME_TRANSPORT_FORWARD PathClass = 2
	PathClass_PATH_CLASS_CROSS_TRANSPORT_BRIDGE PathClass = 3
	PathClass_PATH_CLASS_NATIVE_RELAY           PathClass = 4
)

// Enum value maps for PathClass.
var (
	PathClass_name = map[int32]string{
		0: "PATH_CLASS_UNSPECIFIED",
		1: "PATH_CLASS_DIRECT",
		2: "PATH_CLASS_SAME_TRANSPORT_FORWARD",
		3: "PATH_CLASS_CROSS_TRANSPORT_BRIDGE",
		4: "PATH_CLASS_NATIVE_RELAY",
	}
	PathClass_value = map[string]int32{
		"PATH_CLASS_UNSPECIFIED":            0,
		"PATH_CLASS_DIRECT":                 1,
		"PATH_CLASS_SAME_TRANSPORT_FORWARD": 2,
		"PATH_CLASS_CROSS_TRANSPORT_BRIDGE": 3,
		"PATH_CLASS_NATIVE_RELAY":           4,
	}
)

func (x PathClass) Enum() *PathClass {
	p := new(PathClass)
	*p = x
	return p
}

func (x PathClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PathClass) Descriptor() protoreflect.EnumDescriptor {
	return file_mesh_proto_enumTypes[3].Descriptor()
}

func (PathClass) Type() protoreflect.EnumType {
	return &file_mesh_proto_enumTypes[3]
}

func (x PathClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PathClass.Descriptor instead.
func (PathClass) EnumDescriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{3}
}

type ClusterEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ClusterEnvelope_NodeHello
	//	*ClusterEnvelope_TimeSyncRequest
	//	*ClusterEnvelope_TimeSyncResponse
	//	*ClusterEnvelope_TopologyUpdate
	//	*ClusterEnvelope_QueryRequest
	//	*ClusterEnvelope_QueryResponse
	//	*ClusterEnvelope_ForwardedPacket
	//	*ClusterEnvelope_ReplicationBatch
	//	*ClusterEnvelope_PullRequest
	//	*ClusterEnvelope_SnapshotManifest
	//	*ClusterEnvelope_SnapshotChunk
	//	*ClusterEnvelope_RouteDiagnostic
	Body          isClusterEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterEnvelope) Reset() {
	*x = ClusterEnvelope{}
	mi := &file_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterEnvelope) ProtoMessage() {}

func (x *ClusterEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterEnvelope.ProtoReflect.Descriptor instead.
func (*ClusterEnvelope) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterEnvelope) GetBody() isClusterEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ClusterEnvelope) GetNodeHello() *MeshNodeHello {
	if x != nil {
		if x, ok := x.Body.(*ClusterEnvelope_NodeHello); ok {
			return x.NodeHello
		}
	}
	return nil
}

func (x *ClusterEnvelope) GetTimeSyncRequest() *MeshTimeSyncRequest {
	if x != nil {
		if x, ok := x.Body.(*ClusterEnvelope_TimeSyncRequest); ok {
			return x.TimeSyncRequest
		}
	}
	return nil
}

func (x *ClusterEnvelope) GetTimeSyncResponse() *MeshTimeSyncResponse {
	if x != nil {
		if x, ok := x.Body.(*ClusterEnvelope_TimeSyncResponse); ok {
			return x.TimeSyncResponse
		}
	}
	return nil
}

func (x *ClusterEnvelope) GetTopologyUpdate() *MeshTopologyUpdate {
	if x != nil {
		if x, ok := x.Body.(*ClusterEnvelope_TopologyUpdate); ok {
			return x.TopologyUpdate
		}
	}
	return nil
}

func (x *ClusterEnvelope) GetQueryRequest() *MeshQueryRequest {
	if x != nil {
		if x, ok := x.Body.(*ClusterEnvelope_QueryRequest); ok {
			return x.QueryRequest
		}
	}
	return nil
}

func (x *ClusterEnvelope) GetQueryResponse() *MeshQueryResponse {
	if x != nil {
		if x, ok := x.Body.(*ClusterEnvelope_QueryResponse); ok {
			return x.QueryResponse
		}
	}
	return nil
}

func (x *ClusterEnvelope) GetForwardedPacket() *MeshForwardedPacket {
	if x != nil {
		if x, ok := x.Body.(*ClusterEnvelope_ForwardedPacket); ok {
			return x.ForwardedPacket
		}
	}
	return nil
}

func (x *ClusterEnvelope) GetReplicationBatch() *MeshReplicationBatch {
	if x != nil {
		if x, ok := x.Body.(*ClusterEnvelope_ReplicationBatch); ok {
			return x.ReplicationBatch
		}
	}
	return nil
}

func (x *ClusterEnvelope) GetPullRequest() *MeshPullRequest {
	if x != nil {
		if x, ok := x.Body.(*ClusterEnvelope_PullRequest); ok {
			return x.PullRequest
		}
	}
	return nil
}

func (x *ClusterEnvelope) GetSnapshotManifest() *MeshSnapshotManifest {
	if x != nil {
		if x, ok := x.Body.(*ClusterEnvelope_SnapshotManifest); ok {
			return x.SnapshotManifest
		}
	}
	return nil
}

func (x *ClusterEnvelope) GetSnapshotChunk() *MeshSnapshotChunk {
	if x != nil {
		if x, ok := x.Body.(*ClusterEnvelope_SnapshotChunk); ok {
			return x.SnapshotChunk
		}
	}
	return nil
}

func (x *ClusterEnvelope) GetRouteDiagnostic() *MeshRouteDiagnostic {
	if x != nil {
		if x, ok := x.Body.(*ClusterEnvelope_RouteDiagnostic); ok {
			return x.RouteDiagnostic
		}
	}
	return nil
}

type isClusterEnvelope_Body interface {
	isClusterEnvelope_Body()
}

type ClusterEnvelope_NodeHello struct {
	NodeHello *MeshNodeHello `protobuf:"bytes,1,opt,name=node_hello,json=nodeHello,proto3,oneof"`
}

type ClusterEnvelope_TimeSyncRequest struct {
	TimeSyncRequest *MeshTimeSyncRequest `protobuf:"bytes,2,opt,name=time_sync_request,json=timeSyncRequest,proto3,oneof"`
}

type ClusterEnvelope_TimeSyncResponse struct {
	TimeSyncResponse *MeshTimeSyncResponse `protobuf:"bytes,3,opt,name=time_sync_response,json=timeSyncResponse,proto3,oneof"`
}

type ClusterEnvelope_TopologyUpdate struct {
	TopologyUpdate *MeshTopologyUpdate `protobuf:"bytes,4,opt,name=topology_update,json=topologyUpdate,proto3,oneof"`
}

type ClusterEnvelope_QueryRequest struct {
	QueryRequest *MeshQueryRequest `protobuf:"bytes,5,opt,name=query_request,json=queryRequest,proto3,oneof"`
}

type ClusterEnvelope_QueryResponse struct {
	QueryResponse *MeshQueryResponse `protobuf:"bytes,6,opt,name=query_response,json=queryResponse,proto3,oneof"`
}

type ClusterEnvelope_ForwardedPacket struct {
	ForwardedPacket *MeshForwardedPacket `protobuf:"bytes,7,opt,name=forwarded_packet,json=forwardedPacket,proto3,oneof"`
}

type ClusterEnvelope_ReplicationBatch struct {
	ReplicationBatch *MeshReplicationBatch `protobuf:"bytes,8,opt,name=replication_batch,json=replicationBatch,proto3,oneof"`
}

type ClusterEnvelope_PullRequest struct {
	PullRequest *MeshPullRequest `protobuf:"bytes,9,opt,name=pull_request,json=pullRequest,proto3,oneof"`
}

type ClusterEnvelope_SnapshotManifest struct {
	SnapshotManifest *MeshSnapshotManifest `protobuf:"bytes,10,opt,name=snapshot_manifest,json=snapshotManifest,proto3,oneof"`
}

type ClusterEnvelope_SnapshotChunk struct {
	SnapshotChunk *MeshSnapshotChunk `protobuf:"bytes,11,opt,name=snapshot_chunk,json=snapshotChunk,proto3,oneof"`
}

type ClusterEnvelope_RouteDiagnostic struct {
	RouteDiagnostic *MeshRouteDiagnostic `protobuf:"bytes,12,opt,name=route_diagnostic,json=routeDiagnostic,proto3,oneof"`
}

func (*ClusterEnvelope_NodeHello) isClusterEnvelope_Body() {}

func (*ClusterEnvelope_TimeSyncRequest) isClusterEnvelope_Body() {}

func (*ClusterEnvelope_TimeSyncResponse) isClusterEnvelope_Body() {}

func (*ClusterEnvelope_TopologyUpdate) isClusterEnvelope_Body() {}

func (*ClusterEnvelope_QueryRequest) isClusterEnvelope_Body() {}

func (*ClusterEnvelope_QueryResponse) isClusterEnvelope_Body() {}

func (*ClusterEnvelope_ForwardedPacket) isClusterEnvelope_Body() {}

func (*ClusterEnvelope_ReplicationBatch) isClusterEnvelope_Body() {}

func (*ClusterEnvelope_PullRequest) isClusterEnvelope_Body() {}

func (*ClusterEnvelope_SnapshotManifest) isClusterEnvelope_Body() {}

func (*ClusterEnvelope_SnapshotChunk) isClusterEnvelope_Body() {}

func (*ClusterEnvelope_RouteDiagnostic) isClusterEnvelope_Body() {}

type MeshNodeHello struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	NodeId           int64                      `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ProtocolVersion  string                     `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Transports       []*MeshTransportCapability `protobuf:"bytes,3,rep,name=transports,proto3" json:"transports,omitempty"`
	ForwardingPolicy *MeshForwardingPolicy      `protobuf:"bytes,4,opt,name=forwarding_policy,json=forwardingPolicy,proto3" json:"forwarding_policy,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MeshNodeHello) Reset() {
	*x = MeshNodeHello{}
	mi := &file_mesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshNodeHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshNodeHello) ProtoMessage() {}

func (x *MeshNodeHello) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshNodeHello.ProtoReflect.Descriptor instead.
func (*MeshNodeHello) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{1}
}

func (x *MeshNodeHello) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *MeshNodeHello) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *MeshNodeHello) GetTransports() []*MeshTransportCapability {
	if x != nil {
		return x.Transports
	}
	return nil
}

func (x *MeshNodeHello) GetForwardingPolicy() *MeshForwardingPolicy {
	if x != nil {
		return x.ForwardingPolicy
	}
	return nil
}

type MeshTransportCapability struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Transport                 TransportKind          `protobuf:"varint,1,opt,name=transport,proto3,enum=notifier.mesh.v1.TransportKind" json:"transport,omitempty"`
	InboundEnabled            bool                   `protobuf:"varint,2,opt,name=inbound_enabled,json=inboundEnabled,proto3" json:"inbound_enabled,omitempty"`
	OutboundEnabled           bool                   `protobuf:"varint,3,opt,name=outbound_enabled,json=outboundEnabled,proto3" json:"outbound_enabled,omitempty"`
	NativeRelayClientEnabled  bool                   `protobuf:"varint,4,opt,name=native_relay_client_enabled,json=nativeRelayClientEnabled,proto3" json:"native_relay_client_enabled,omitempty"`
	NativeRelayServiceEnabled bool                   `protobuf:"varint,5,opt,name=native_relay_service_enabled,json=nativeRelayServiceEnabled,proto3" json:"native_relay_service_enabled,omitempty"`
	AdvertisedEndpoints       []string               `protobuf:"bytes,6,rep,name=advertised_endpoints,json=advertisedEndpoints,proto3" json:"advertised_endpoints,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *MeshTransportCapability) Reset() {
	*x = MeshTransportCapability{}
	mi := &file_mesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshTransportCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshTransportCapability) ProtoMessage() {}

func (x *MeshTransportCapability) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshTransportCapability.ProtoReflect.Descriptor instead.
func (*MeshTransportCapability) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{2}
}

func (x *MeshTransportCapability) GetTransport() TransportKind {
	if x != nil {
		return x.Transport
	}
	return TransportKind_TRANSPORT_KIND_UNSPECIFIED
}

func (x *MeshTransportCapability) GetInboundEnabled() bool {
	if x != nil {
		return x.InboundEnabled
	}
	return false
}

func (x *MeshTransportCapability) GetOutboundEnabled() bool {
	if x != nil {
		return x.OutboundEnabled
	}
	return false
}

func (x *MeshTransportCapability) GetNativeRelayClientEnabled() bool {
	if x != nil {
		return x.NativeRelayClientEnabled
	}
	return false
}

func (x *MeshTransportCapability) GetNativeRelayServiceEnabled() bool {
	if x != nil {
		return x.NativeRelayServiceEnabled
	}
	return false
}

func (x *MeshTransportCapability) GetAdvertisedEndpoints() []string {
	if x != nil {
		return x.AdvertisedEndpoints
	}
	return nil
}

type MeshForwardingPolicy struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransitEnabled bool                   `protobuf:"varint,1,opt,name=transit_enabled,json=transitEnabled,proto3" json:"transit_enabled,omitempty"`
	BridgeEnabled  bool                   `protobuf:"varint,2,opt,name=bridge_enabled,json=bridgeEnabled,proto3" json:"bridge_enabled,omitempty"`
	NodeFeeWeight  int64                  `protobuf:"varint,3,opt,name=node_fee_weight,json=nodeFeeWeight,proto3" json:"node_fee_weight,omitempty"`
	TrafficRules   []*MeshTrafficRule     `protobuf:"bytes,4,rep,name=traffic_rules,json=trafficRules,proto3" json:"traffic_rules,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MeshForwardingPolicy) Reset() {
	*x = MeshForwardingPolicy{}
	mi := &file_mesh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshForwardingPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshForwardingPolicy) ProtoMessage() {}

func (x *MeshForwardingPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshForwardingPolicy.ProtoReflect.Descriptor instead.
func (*MeshForwardingPolicy) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{3}
}

func (x *MeshForwardingPolicy) GetTransitEnabled() bool {
	if x != nil {
		return x.TransitEnabled
	}
	return false
}

func (x *MeshForwardingPolicy) GetBridgeEnabled() bool {
	if x != nil {
		return x.BridgeEnabled
	}
	return false
}

func (x *MeshForwardingPolicy) GetNodeFeeWeight() int64 {
	if x != nil {
		return x.NodeFeeWeight
	}
	return 0
}

func (x *MeshForwardingPolicy) GetTrafficRules() []*MeshTrafficRule {
	if x != nil {
		return x.TrafficRules
	}
	return nil
}

type MeshTrafficRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrafficClass  TrafficClass           `protobuf:"varint,1,opt,name=traffic_class,json=trafficClass,proto3,enum=notifier.mesh.v1.TrafficClass" json:"traffic_class,omitempty"`
	Disposition   ForwardingDisposition  `protobuf:"varint,2,opt,name=disposition,proto3,enum=notifier.mesh.v1.ForwardingDisposition" json:"disposition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshTrafficRule) Reset() {
	*x = MeshTrafficRule{}
	mi := &file_mesh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshTrafficRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshTrafficRule) ProtoMessage() {}

func (x *MeshTrafficRule) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshTrafficRule.ProtoReflect.Descriptor instead.
func (*MeshTrafficRule) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{4}
}

func (x *MeshTrafficRule) GetTrafficClass() TrafficClass {
	if x != nil {
		return x.TrafficClass
	}
	return TrafficClass_TRAFFIC_CLASS_UNSPECIFIED
}

func (x *MeshTrafficRule) GetDisposition() ForwardingDisposition {
	if x != nil {
		return x.Disposition
	}
	return ForwardingDisposition_FORWARDING_DISPOSITION_UNSPECIFIED
}

type MeshTopologyUpdate struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	OriginNodeId     int64                    `protobuf:"varint,1,opt,name=origin_node_id,json=originNodeId,proto3" json:"origin_node_id,omitempty"`
	Generation       uint64                   `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	Links            []*MeshLinkAdvertisement `protobuf:"bytes,3,rep,name=links,proto3" json:"links,omitempty"`
	ForwardingPolicy *MeshForwardingPolicy    `protobuf:"bytes,4,opt,name=forwarding_policy,json=forwardingPolicy,proto3" json:"forwarding_policy,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MeshTopologyUpdate) Reset() {
	*x = MeshTopologyUpdate{}
	mi := &file_mesh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshTopologyUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshTopologyUpdate) ProtoMessage() {}

func (x *MeshTopologyUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshTopologyUpdate.ProtoReflect.Descriptor instead.
func (*MeshTopologyUpdate) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{5}
}

func (x *MeshTopologyUpdate) GetOriginNodeId() int64 {
	if x != nil {
		return x.OriginNodeId
	}
	return 0
}

func (x *MeshTopologyUpdate) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *MeshTopologyUpdate) GetLinks() []*MeshLinkAdvertisement {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *MeshTopologyUpdate) GetForwardingPolicy() *MeshForwardingPolicy {
	if x != nil {
		return x.ForwardingPolicy
	}
	return nil
}

type MeshLinkAdvertisement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNodeId    int64                  `protobuf:"varint,1,opt,name=from_node_id,json=fromNodeId,proto3" json:"from_node_id,omitempty"`
	ToNodeId      int64                  `protobuf:"varint,2,opt,name=to_node_id,json=toNodeId,proto3" json:"to_node_id,omitempty"`
	Transport     TransportKind          `protobuf:"varint,3,opt,name=transport,proto3,enum=notifier.mesh.v1.TransportKind" json:"transport,omitempty"`
	PathClass     PathClass              `protobuf:"varint,4,opt,name=path_class,json=pathClass,proto3,enum=notifier.mesh.v1.PathClass" json:"path_class,omitempty"`
	CostMs        uint32                 `protobuf:"varint,5,opt,name=cost_ms,json=costMs,proto3" json:"cost_ms,omitempty"`
	JitterMs      uint32                 `protobuf:"varint,6,opt,name=jitter_ms,json=jitterMs,proto3" json:"jitter_ms,omitempty"`
	Established   bool                   `protobuf:"varint,7,opt,name=established,proto3" json:"established,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshLinkAdvertisement) Reset() {
	*x = MeshLinkAdvertisement{}
	mi := &file_mesh_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshLinkAdvertisement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshLinkAdvertisement) ProtoMessage() {}

func (x *MeshLinkAdvertisement) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshLinkAdvertisement.ProtoReflect.Descriptor instead.
func (*MeshLinkAdvertisement) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{6}
}

func (x *MeshLinkAdvertisement) GetFromNodeId() int64 {
	if x != nil {
		return x.FromNodeId
	}
	return 0
}

func (x *MeshLinkAdvertisement) GetToNodeId() int64 {
	if x != nil {
		return x.ToNodeId
	}
	return 0
}

func (x *MeshLinkAdvertisement) GetTransport() TransportKind {
	if x != nil {
		return x.Transport
	}
	return TransportKind_TRANSPORT_KIND_UNSPECIFIED
}

func (x *MeshLinkAdvertisement) GetPathClass() PathClass {
	if x != nil {
		return x.PathClass
	}
	return PathClass_PATH_CLASS_UNSPECIFIED
}

func (x *MeshLinkAdvertisement) GetCostMs() uint32 {
	if x != nil {
		return x.CostMs
	}
	return 0
}

func (x *MeshLinkAdvertisement) GetJitterMs() uint32 {
	if x != nil {
		return x.JitterMs
	}
	return 0
}

func (x *MeshLinkAdvertisement) GetEstablished() bool {
	if x != nil {
		return x.Established
	}
	return false
}

type MeshForwardedPacket struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PacketId         uint64                 `protobuf:"varint,1,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"`
	SourceNodeId     int64                  `protobuf:"varint,2,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	TargetNodeId     int64                  `protobuf:"varint,3,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	TrafficClass     TrafficClass           `protobuf:"varint,4,opt,name=traffic_class,json=trafficClass,proto3,enum=notifier.mesh.v1.TrafficClass" json:"traffic_class,omitempty"`
	LastHopNodeId    int64                  `protobuf:"varint,5,opt,name=last_hop_node_id,json=lastHopNodeId,proto3" json:"last_hop_node_id,omitempty"`
	IngressTransport TransportKind          `protobuf:"varint,6,opt,name=ingress_transport,json=ingressTransport,proto3,enum=notifier.mesh.v1.TransportKind" json:"ingress_transport,omitempty"`
	TtlHops          uint32                 `protobuf:"varint,7,opt,name=ttl_hops,json=ttlHops,proto3" json:"ttl_hops,omitempty"`
	Payload          []byte                 `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	TraceId          string                 `protobuf:"bytes,9,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MeshForwardedPacket) Reset() {
	*x = MeshForwardedPacket{}
	mi := &file_mesh_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshForwardedPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshForwardedPacket) ProtoMessage() {}

func (x *MeshForwardedPacket) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshForwardedPacket.ProtoReflect.Descriptor instead.
func (*MeshForwardedPacket) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{7}
}

func (x *MeshForwardedPacket) GetPacketId() uint64 {
	if x != nil {
		return x.PacketId
	}
	return 0
}

func (x *MeshForwardedPacket) GetSourceNodeId() int64 {
	if x != nil {
		return x.SourceNodeId
	}
	return 0
}

func (x *MeshForwardedPacket) GetTargetNodeId() int64 {
	if x != nil {
		return x.TargetNodeId
	}
	return 0
}

func (x *MeshForwardedPacket) GetTrafficClass() TrafficClass {
	if x != nil {
		return x.TrafficClass
	}
	return TrafficClass_TRAFFIC_CLASS_UNSPECIFIED
}

func (x *MeshForwardedPacket) GetLastHopNodeId() int64 {
	if x != nil {
		return x.LastHopNodeId
	}
	return 0
}

func (x *MeshForwardedPacket) GetIngressTransport() TransportKind {
	if x != nil {
		return x.IngressTransport
	}
	return TransportKind_TRANSPORT_KIND_UNSPECIFIED
}

func (x *MeshForwardedPacket) GetTtlHops() uint32 {
	if x != nil {
		return x.TtlHops
	}
	return 0
}

func (x *MeshForwardedPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MeshForwardedPacket) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type MeshReplicationBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginNodeId  int64                  `protobuf:"varint,1,opt,name=origin_node_id,json=originNodeId,proto3" json:"origin_node_id,omitempty"`
	BatchId       uint64                 `protobuf:"varint,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshReplicationBatch) Reset() {
	*x = MeshReplicationBatch{}
	mi := &file_mesh_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshReplicationBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshReplicationBatch) ProtoMessage() {}

func (x *MeshReplicationBatch) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshReplicationBatch.ProtoReflect.Descriptor instead.
func (*MeshReplicationBatch) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{8}
}

func (x *MeshReplicationBatch) GetOriginNodeId() int64 {
	if x != nil {
		return x.OriginNodeId
	}
	return 0
}

func (x *MeshReplicationBatch) GetBatchId() uint64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *MeshReplicationBatch) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type MeshPullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginNodeId  int64                  `protobuf:"varint,1,opt,name=origin_node_id,json=originNodeId,proto3" json:"origin_node_id,omitempty"`
	AfterSequence uint64                 `protobuf:"varint,2,opt,name=after_sequence,json=afterSequence,proto3" json:"after_sequence,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshPullRequest) Reset() {
	*x = MeshPullRequest{}
	mi := &file_mesh_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshPullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshPullRequest) ProtoMessage() {}

func (x *MeshPullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshPullRequest.ProtoReflect.Descriptor instead.
func (*MeshPullRequest) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{9}
}

func (x *MeshPullRequest) GetOriginNodeId() int64 {
	if x != nil {
		return x.OriginNodeId
	}
	return 0
}

func (x *MeshPullRequest) GetAfterSequence() uint64 {
	if x != nil {
		return x.AfterSequence
	}
	return 0
}

func (x *MeshPullRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type MeshSnapshotManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Partitions    []string               `protobuf:"bytes,2,rep,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshSnapshotManifest) Reset() {
	*x = MeshSnapshotManifest{}
	mi := &file_mesh_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshSnapshotManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshSnapshotManifest) ProtoMessage() {}

func (x *MeshSnapshotManifest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshSnapshotManifest.ProtoReflect.Descriptor instead.
func (*MeshSnapshotManifest) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{10}
}

func (x *MeshSnapshotManifest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *MeshSnapshotManifest) GetPartitions() []string {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type MeshSnapshotChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Partition     string                 `protobuf:"bytes,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshSnapshotChunk) Reset() {
	*x = MeshSnapshotChunk{}
	mi := &file_mesh_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshSnapshotChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshSnapshotChunk) ProtoMessage() {}

func (x *MeshSnapshotChunk) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshSnapshotChunk.ProtoReflect.Descriptor instead.
func (*MeshSnapshotChunk) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{11}
}

func (x *MeshSnapshotChunk) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *MeshSnapshotChunk) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *MeshSnapshotChunk) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type MeshTimeSyncRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ClientSendTimeMs int64                  `protobuf:"varint,2,opt,name=client_send_time_ms,json=clientSendTimeMs,proto3" json:"client_send_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MeshTimeSyncRequest) Reset() {
	*x = MeshTimeSyncRequest{}
	mi := &file_mesh_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshTimeSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshTimeSyncRequest) ProtoMessage() {}

func (x *MeshTimeSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshTimeSyncRequest.ProtoReflect.Descriptor instead.
func (*MeshTimeSyncRequest) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{12}
}

func (x *MeshTimeSyncRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *MeshTimeSyncRequest) GetClientSendTimeMs() int64 {
	if x != nil {
		return x.ClientSendTimeMs
	}
	return 0
}

type MeshTimeSyncResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RequestId           uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ClientSendTimeMs    int64                  `protobuf:"varint,2,opt,name=client_send_time_ms,json=clientSendTimeMs,proto3" json:"client_send_time_ms,omitempty"`
	ServerReceiveTimeMs int64                  `protobuf:"varint,3,opt,name=server_receive_time_ms,json=serverReceiveTimeMs,proto3" json:"server_receive_time_ms,omitempty"`
	ServerSendTimeMs    int64                  `protobuf:"varint,4,opt,name=server_send_time_ms,json=serverSendTimeMs,proto3" json:"server_send_time_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MeshTimeSyncResponse) Reset() {
	*x = MeshTimeSyncResponse{}
	mi := &file_mesh_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshTimeSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshTimeSyncResponse) ProtoMessage() {}

func (x *MeshTimeSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshTimeSyncResponse.ProtoReflect.Descriptor instead.
func (*MeshTimeSyncResponse) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{13}
}

func (x *MeshTimeSyncResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *MeshTimeSyncResponse) GetClientSendTimeMs() int64 {
	if x != nil {
		return x.ClientSendTimeMs
	}
	return 0
}

func (x *MeshTimeSyncResponse) GetServerReceiveTimeMs() int64 {
	if x != nil {
		return x.ServerReceiveTimeMs
	}
	return 0
}

func (x *MeshTimeSyncResponse) GetServerSendTimeMs() int64 {
	if x != nil {
		return x.ServerSendTimeMs
	}
	return 0
}

type MeshQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshQueryRequest) Reset() {
	*x = MeshQueryRequest{}
	mi := &file_mesh_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshQueryRequest) ProtoMessage() {}

func (x *MeshQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshQueryRequest.ProtoReflect.Descriptor instead.
func (*MeshQueryRequest) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{14}
}

func (x *MeshQueryRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *MeshQueryRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *MeshQueryRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type MeshQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshQueryResponse) Reset() {
	*x = MeshQueryResponse{}
	mi := &file_mesh_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshQueryResponse) ProtoMessage() {}

func (x *MeshQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshQueryResponse.ProtoReflect.Descriptor instead.
func (*MeshQueryResponse) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{15}
}

func (x *MeshQueryResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *MeshQueryResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *MeshQueryResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *MeshQueryResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type MeshRouteDiagnostic struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DestinationNodeId int64                  `protobuf:"varint,1,opt,name=destination_node_id,json=destinationNodeId,proto3" json:"destination_node_id,omitempty"`
	TrafficClass      TrafficClass           `protobuf:"varint,2,opt,name=traffic_class,json=trafficClass,proto3,enum=notifier.mesh.v1.TrafficClass" json:"traffic_class,omitempty"`
	IngressTransport  TransportKind          `protobuf:"varint,3,opt,name=ingress_transport,json=ingressTransport,proto3,enum=notifier.mesh.v1.TransportKind" json:"ingress_transport,omitempty"`
	Message           string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MeshRouteDiagnostic) Reset() {
	*x = MeshRouteDiagnostic{}
	mi := &file_mesh_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshRouteDiagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshRouteDiagnostic) ProtoMessage() {}

func (x *MeshRouteDiagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshRouteDiagnostic.ProtoReflect.Descriptor instead.
func (*MeshRouteDiagnostic) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{16}
}

func (x *MeshRouteDiagnostic) GetDestinationNodeId() int64 {
	if x != nil {
		return x.DestinationNodeId
	}
	return 0
}

func (x *MeshRouteDiagnostic) GetTrafficClass() TrafficClass {
	if x != nil {
		return x.TrafficClass
	}
	return TrafficClass_TRAFFIC_CLASS_UNSPECIFIED
}

func (x *MeshRouteDiagnostic) GetIngressTransport() TransportKind {
	if x != nil {
		return x.IngressTransport
	}
	return TransportKind_TRANSPORT_KIND_UNSPECIFIED
}

func (x *MeshRouteDiagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_mesh_proto protoreflect.FileDescriptor

const file_mesh_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"mesh.proto\x12\x10notifier.mesh.v1\"\xde\a\n" +
	"\x0fClusterEnvelope\x12@\n" +
	"\n" +
	"node_hello\x18\x01 \x01(\v2\x1f.notifier.mesh.v1.MeshNodeHelloH\x00R\tnodeHello\x12S\n" +
	"\x11time_sync_request\x18\x02 \x01(\v2%.notifier.mesh.v1.MeshTimeSyncRequestH\x00R\x0ftimeSyncRequest\x12V\n" +
	"\x12time_sync_response\x18\x03 \x01(\v2&.notifier.mesh.v1.MeshTimeSyncResponseH\x00R\x10timeSyncResponse\x12O\n" +
	"\x0ftopology_update\x18\x04 \x01(\v2$.notifier.mesh.v1.MeshTopologyUpdateH\x00R\x0etopologyUpdate\x12I\n" +
	"\rquery_request\x18\x05 \x01(\v2\".notifier.mesh.v1.MeshQueryRequestH\x00R\fqueryRequest\x12L\n" +
	"\x0equery_response\x18\x06 \x01(\v2#.notifier.mesh.v1.MeshQueryResponseH\x00R\rqueryResponse\x12R\n" +
	"\x10forwarded_packet\x18\a \x01(\v2%.notifier.mesh.v1.MeshForwardedPacketH\x00R\x0fforwardedPacket\x12U\n" +
	"\x11replication_batch\x18\b \x01(\v2&.notifier.mesh.v1.MeshReplicationBatchH\x00R\x10replicationBatch\x12F\n" +
	"\fpull_request\x18\t \x01(\v2!.notifier.mesh.v1.MeshPullRequestH\x00R\vpullRequest\x12U\n" +
	"\x11snapshot_manifest\x18\n" +
	" \x01(\v2&.notifier.mesh.v1.MeshSnapshotManifestH\x00R\x10snapshotManifest\x12L\n" +
	"\x0esnapshot_chunk\x18\v \x01(\v2#.notifier.mesh.v1.MeshSnapshotChunkH\x00R\rsnapshotChunk\x12R\n" +
	"\x10route_diagnostic\x18\f \x01(\v2%.notifier.mesh.v1.MeshRouteDiagnosticH\x00R\x0frouteDiagnosticB\x06\n" +
	"\x04body\"\xf3\x01\n" +
	"\rMeshNodeHello\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x12I\n" +
	"\n" +
	"transports\x18\x03 \x03(\v2).notifier.mesh.v1.MeshTransportCapabilityR\n" +
	"transports\x12S\n" +
	"\x11forwarding_policy\x18\x04 \x01(\v2&.notifier.mesh.v1.MeshForwardingPolicyR\x10forwardingPolicy\"\xdf\x02\n" +
	"\x17MeshTransportCapability\x12=\n" +
	"\ttransport\x18\x01 \x01(\x0e2\x1f.notifier.mesh.v1.TransportKindR\ttransport\x12'\n" +
	"\x0finbound_enabled\x18\x02 \x01(\bR\x0einboundEnabled\x12)\n" +
	"\x10outbound_enabled\x18\x03 \x01(\bR\x0foutboundEnabled\x12=\n" +
	"\x1bnative_relay_client_enabled\x18\x04 \x01(\bR\x18nativeRelayClientEnabled\x12?\n" +
	"\x1cnative_relay_service_enabled\x18\x05 \x01(\bR\x19nativeRelayServiceEnabled\x121\n" +
	"\x14advertised_endpoints\x18\x06 \x03(\tR\x13advertisedEndpoints\"\xd6\x01\n" +
	"\x14MeshForwardingPolicy\x12'\n" +
	"\x0ftransit_enabled\x18\x01 \x01(\bR\x0etransitEnabled\x12%\n" +
	"\x0ebridge_enabled\x18\x02 \x01(\bR\rbridgeEnabled\x12&\n" +
	"\x0fnode_fee_weight\x18\x03 \x01(\x03R\rnodeFeeWeight\x12F\n" +
	"\rtraffic_rules\x18\x04 \x03(\v2!.notifier.mesh.v1.MeshTrafficRuleR\ftrafficRules\"\xa1\x01\n" +
	"\x0fMeshTrafficRule\x12C\n" +
	"\rtraffic_class\x18\x01 \x01(\x0e2\x1e.notifier.mesh.v1.TrafficClassR\ftrafficClass\x12I\n" +
	"\vdisposition\x18\x02 \x01(\x0e2'.notifier.mesh.v1.ForwardingDispositionR\vdisposition\"\xee\x01\n" +
	"\x12MeshTopologyUpdate\x12$\n" +
	"\x0eorigin_node_id\x18\x01 \x01(\x03R\foriginNodeId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x12=\n" +
	"\x05links\x18\x03 \x03(\v2'.notifier.mesh.v1.MeshLinkAdvertisementR\x05links\x12S\n" +
	"\x11forwarding_policy\x18\x04 \x01(\v2&.notifier.mesh.v1.MeshForwardingPolicyR\x10forwardingPolicy\"\xaa\x02\n" +
	"\x15MeshLinkAdvertisement\x12 \n" +
	"\ffrom_node_id\x18\x01 \x01(\x03R\n" +
	"fromNodeId\x12\x1c\n" +
	"\n" +
	"to_node_id\x18\x02 \x01(\x03R\btoNodeId\x12=\n" +
	"\ttransport\x18\x03 \x01(\x0e2\x1f.notifier.mesh.v1.TransportKindR\ttransport\x12:\n" +
	"\n" +
	"path_class\x18\x04 \x01(\x0e2\x1b.notifier.mesh.v1.PathClassR\tpathClass\x12\x17\n" +
	"\acost_ms\x18\x05 \x01(\rR\x06costMs\x12\x1b\n" +
	"\tjitter_ms\x18\x06 \x01(\rR\bjitterMs\x12 \n" +
	"\vestablished\x18\a \x01(\bR\vestablished\"\x8a\x03\n" +
	"\x13MeshForwardedPacket\x12\x1b\n" +
	"\tpacket_id\x18\x01 \x01(\x04R\bpacketId\x12$\n" +
	"\x0esource_node_id\x18\x02 \x01(\x03R\fsourceNodeId\x12$\n" +
	"\x0etarget_node_id\x18\x03 \x01(\x03R\ftargetNodeId\x12C\n" +
	"\rtraffic_class\x18\x04 \x01(\x0e2\x1e.notifier.mesh.v1.TrafficClassR\ftrafficClass\x12'\n" +
	"\x10last_hop_node_id\x18\x05 \x01(\x03R\rlastHopNodeId\x12L\n" +
	"\x11ingress_transport\x18\x06 \x01(\x0e2\x1f.notifier.mesh.v1.TransportKindR\x10ingressTransport\x12\x19\n" +
	"\bttl_hops\x18\a \x01(\rR\attlHops\x12\x18\n" +
	"\apayload\x18\b \x01(\fR\apayload\x12\x19\n" +
	"\btrace_id\x18\t \x01(\tR\atraceId\"q\n" +
	"\x14MeshReplicationBatch\x12$\n" +
	"\x0eorigin_node_id\x18\x01 \x01(\x03R\foriginNodeId\x12\x19\n" +
	"\bbatch_id\x18\x02 \x01(\x04R\abatchId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"t\n" +
	"\x0fMeshPullRequest\x12$\n" +
	"\x0eorigin_node_id\x18\x01 \x01(\x03R\foriginNodeId\x12%\n" +
	"\x0eafter_sequence\x18\x02 \x01(\x04R\rafterSequence\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"W\n" +
	"\x14MeshSnapshotManifest\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x1e\n" +
	"\n" +
	"partitions\x18\x02 \x03(\tR\n" +
	"partitions\"l\n" +
	"\x11MeshSnapshotChunk\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\tR\tpartition\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"c\n" +
	"\x13MeshTimeSyncRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12-\n" +
	"\x13client_send_time_ms\x18\x02 \x01(\x03R\x10clientSendTimeMs\"\xc8\x01\n" +
	"\x14MeshTimeSyncResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12-\n" +
	"\x13client_send_time_ms\x18\x02 \x01(\x03R\x10clientSendTimeMs\x123\n" +
	"\x16server_receive_time_ms\x18\x03 \x01(\x03R\x13serverReceiveTimeMs\x12-\n" +
	"\x13server_send_time_ms\x18\x04 \x01(\x03R\x10serverSendTimeMs\"_\n" +
	"\x10MeshQueryRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\x90\x01\n" +
	"\x11MeshQueryResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"\xf2\x01\n" +
	"\x13MeshRouteDiagnostic\x12.\n" +
	"\x13destination_node_id\x18\x01 \x01(\x03R\x11destinationNodeId\x12C\n" +
	"\rtraffic_class\x18\x02 \x01(\x0e2\x1e.notifier.mesh.v1.TrafficClassR\ftrafficClass\x12L\n" +
	"\x11ingress_transport\x18\x03 \x01(\x0e2\x1f.notifier.mesh.v1.TransportKindR\x10ingressTransport\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage*e\n" +
	"\rTransportKind\x12\x1e\n" +
	"\x1aTRANSPORT_KIND_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TRANSPORT_KIND_LIBP2P\x10\x01\x12\x19\n" +
	"\x15TRANSPORT_KIND_ZEROMQ\x10\x02*\xc4\x01\n" +
	"\fTrafficClass\x12\x1d\n" +
	"\x19TRAFFIC_CLASS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TRAFFIC_CONTROL_CRITICAL\x10\x01\x12\x19\n" +
	"\x15TRAFFIC_CONTROL_QUERY\x10\x02\x12!\n" +
	"\x1dTRAFFIC_TRANSIENT_INTERACTIVE\x10\x03\x12\x1e\n" +
	"\x1aTRAFFIC_REPLICATION_STREAM\x10\x04\x12\x19\n" +
	"\x15TRAFFIC_SNAPSHOT_BULK\x10\x05*\xa9\x01\n" +
	"\x15ForwardingDisposition\x12&\n" +
	"\"FORWARDING_DISPOSITION_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cFORWARDING_DISPOSITION_ALLOW\x10\x01\x12%\n" +
	"!FORWARDING_DISPOSITION_DISCOURAGE\x10\x02\x12\x1f\n" +
	"\x1bFORWARDING_DISPOSITION_DENY\x10\x03*\xa9\x01\n" +
	"\tPathClass\x12\x1a\n" +
	"\x16PATH_CLASS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PATH_CLASS_DIRECT\x10\x01\x12%\n" +
	"!PATH_CLASS_SAME_TRANSPORT_FORWARD\x10\x02\x12%\n" +
	"!PATH_CLASS_CROSS_TRANSPORT_BRIDGE\x10\x03\x12\x1b\n" +
	"\x17PATH_CLASS_NATIVE_RELAY\x10\x04B/Z-github.com/tursom/turntf/internal/proto;protob\x06proto3"

var (
	file_mesh_proto_rawDescOnce sync.Once
	file_mesh_proto_rawDescData []byte
)

func file_mesh_proto_rawDescGZIP() []byte {
	file_mesh_proto_rawDescOnce.Do(func() {
		file_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mesh_proto_rawDesc), len(file_mesh_proto_rawDesc)))
	})
	return file_mesh_proto_rawDescData
}

var file_mesh_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_mesh_proto_goTypes = []any{
	(TransportKind)(0),              // 0: notifier.mesh.v1.TransportKind
	(TrafficClass)(0),               // 1: notifier.mesh.v1.TrafficClass
	(ForwardingDisposition)(0),      // 2: notifier.mesh.v1.ForwardingDisposition
	(PathClass)(0),                  // 3: notifier.mesh.v1.PathClass
	(*ClusterEnvelope)(nil),         // 4: notifier.mesh.v1.ClusterEnvelope
	(*MeshNodeHello)(nil),           // 5: notifier.mesh.v1.MeshNodeHello
	(*MeshTransportCapability)(nil), // 6: notifier.mesh.v1.MeshTransportCapability
	(*MeshForwardingPolicy)(nil),    // 7: notifier.mesh.v1.MeshForwardingPolicy
	(*MeshTrafficRule)(nil),         // 8: notifier.mesh.v1.MeshTrafficRule
	(*MeshTopologyUpdate)(nil),      // 9: notifier.mesh.v1.MeshTopologyUpdate
	(*MeshLinkAdvertisement)(nil),   // 10: notifier.mesh.v1.MeshLinkAdvertisement
	(*MeshForwardedPacket)(nil),     // 11: notifier.mesh.v1.MeshForwardedPacket
	(*MeshReplicationBatch)(nil),    // 12: notifier.mesh.v1.MeshReplicationBatch
	(*MeshPullRequest)(nil),         // 13: notifier.mesh.v1.MeshPullRequest
	(*MeshSnapshotManifest)(nil),    // 14: notifier.mesh.v1.MeshSnapshotManifest
	(*MeshSnapshotChunk)(nil),       // 15: notifier.mesh.v1.MeshSnapshotChunk
	(*MeshTimeSyncRequest)(nil),     // 16: notifier.mesh.v1.MeshTimeSyncRequest
	(*MeshTimeSyncResponse)(nil),    // 17: notifier.mesh.v1.MeshTimeSyncResponse
	(*MeshQueryRequest)(nil),        // 18: notifier.mesh.v1.MeshQueryRequest
	(*MeshQueryResponse)(nil),       // 19: notifier.mesh.v1.MeshQueryResponse
	(*MeshRouteDiagnostic)(nil),     // 20: notifier.mesh.v1.MeshRouteDiagnostic
}
var file_mesh_proto_depIdxs = []int32{
	5,  // 0: notifier.mesh.v1.ClusterEnvelope.node_hello:type_name -> notifier.mesh.v1.MeshNodeHello
	16, // 1: notifier.mesh.v1.ClusterEnvelope.time_sync_request:type_name -> notifier.mesh.v1.MeshTimeSyncRequest
	17, // 2: notifier.mesh.v1.ClusterEnvelope.time_sync_response:type_name -> notifier.mesh.v1.MeshTimeSyncResponse
	9,  // 3: notifier.mesh.v1.ClusterEnvelope.topology_update:type_name -> notifier.mesh.v1.MeshTopologyUpdate
	18, // 4: notifier.mesh.v1.ClusterEnvelope.query_request:type_name -> notifier.mesh.v1.MeshQueryRequest
	19, // 5: notifier.mesh.v1.ClusterEnvelope.query_response:type_name -> notifier.mesh.v1.MeshQueryResponse
	11, // 6: notifier.mesh.v1.ClusterEnvelope.forwarded_packet:type_name -> notifier.mesh.v1.MeshForwardedPacket
	12, // 7: notifier.mesh.v1.ClusterEnvelope.replication_batch:type_name -> notifier.mesh.v1.MeshReplicationBatch
	13, // 8: notifier.mesh.v1.ClusterEnvelope.pull_request:type_name -> notifier.mesh.v1.MeshPullRequest
	14, // 9: notifier.mesh.v1.ClusterEnvelope.snapshot_manifest:type_name -> notifier.mesh.v1.MeshSnapshotManifest
	15, // 10: notifier.mesh.v1.ClusterEnvelope.snapshot_chunk:type_name -> notifier.mesh.v1.MeshSnapshotChunk
	20, // 11: notifier.mesh.v1.ClusterEnvelope.route_diagnostic:type_name -> notifier.mesh.v1.MeshRouteDiagnostic
	6,  // 12: notifier.mesh.v1.MeshNodeHello.transports:type_name -> notifier.mesh.v1.MeshTransportCapability
	7,  // 13: notifier.mesh.v1.MeshNodeHello.forwarding_policy:type_name -> notifier.mesh.v1.MeshForwardingPolicy
	0,  // 14: notifier.mesh.v1.MeshTransportCapability.transport:type_name -> notifier.mesh.v1.TransportKind
	8,  // 15: notifier.mesh.v1.MeshForwardingPolicy.traffic_rules:type_name -> notifier.mesh.v1.MeshTrafficRule
	1,  // 16: notifier.mesh.v1.MeshTrafficRule.traffic_class:type_name -> notifier.mesh.v1.TrafficClass
	2,  // 17: notifier.mesh.v1.MeshTrafficRule.disposition:type_name -> notifier.mesh.v1.ForwardingDisposition
	10, // 18: notifier.mesh.v1.MeshTopologyUpdate.links:type_name -> notifier.mesh.v1.MeshLinkAdvertisement
	7,  // 19: notifier.mesh.v1.MeshTopologyUpdate.forwarding_policy:type_name -> notifier.mesh.v1.MeshForwardingPolicy
	0,  // 20: notifier.mesh.v1.MeshLinkAdvertisement.transport:type_name -> notifier.mesh.v1.TransportKind
	3,  // 21: notifier.mesh.v1.MeshLinkAdvertisement.path_class:type_name -> notifier.mesh.v1.PathClass
	1,  // 22: notifier.mesh.v1.MeshForwardedPacket.traffic_class:type_name -> notifier.mesh.v1.TrafficClass
	0,  // 23: notifier.mesh.v1.MeshForwardedPacket.ingress_transport:type_name -> notifier.mesh.v1.TransportKind
	1,  // 24: notifier.mesh.v1.MeshRouteDiagnostic.traffic_class:type_name -> notifier.mesh.v1.TrafficClass
	0,  // 25: notifier.mesh.v1.MeshRouteDiagnostic.ingress_transport:type_name -> notifier.mesh.v1.TransportKind
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_mesh_proto_init() }
func file_mesh_proto_init() {
	if File_mesh_proto != nil {
		return
	}
	file_mesh_proto_msgTypes[0].OneofWrappers = []any{
		(*ClusterEnvelope_NodeHello)(nil),
		(*ClusterEnvelope_TimeSyncRequest)(nil),
		(*ClusterEnvelope_TimeSyncResponse)(nil),
		(*ClusterEnvelope_TopologyUpdate)(nil),
		(*ClusterEnvelope_QueryRequest)(nil),
		(*ClusterEnvelope_QueryResponse)(nil),
		(*ClusterEnvelope_ForwardedPacket)(nil),
		(*ClusterEnvelope_ReplicationBatch)(nil),
		(*ClusterEnvelope_PullRequest)(nil),
		(*ClusterEnvelope_SnapshotManifest)(nil),
		(*ClusterEnvelope_SnapshotChunk)(nil),
		(*ClusterEnvelope_RouteDiagnostic)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mesh_proto_rawDesc), len(file_mesh_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mesh_proto_goTypes,
		DependencyIndexes: file_mesh_proto_depIdxs,
		EnumInfos:         file_mesh_proto_enumTypes,
		MessageInfos:      file_mesh_proto_msgTypes,
	}.Build()
	File_mesh_proto = out.File
	file_mesh_proto_goTypes = nil
	file_mesh_proto_depIdxs = nil
}
