// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: transport.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ZeroMQMuxHello_Role int32

const (
	ZeroMQMuxHello_ZERO_MQ_ROLE_UNSPECIFIED ZeroMQMuxHello_Role = 0
	ZeroMQMuxHello_ZERO_MQ_ROLE_CLUSTER     ZeroMQMuxHello_Role = 1
	ZeroMQMuxHello_ZERO_MQ_ROLE_CLIENT      ZeroMQMuxHello_Role = 2
)

// Enum value maps for ZeroMQMuxHello_Role.
var (
	ZeroMQMuxHello_Role_name = map[int32]string{
		0: "ZERO_MQ_ROLE_UNSPECIFIED",
		1: "ZERO_MQ_ROLE_CLUSTER",
		2: "ZERO_MQ_ROLE_CLIENT",
	}
	ZeroMQMuxHello_Role_value = map[string]int32{
		"ZERO_MQ_ROLE_UNSPECIFIED": 0,
		"ZERO_MQ_ROLE_CLUSTER":     1,
		"ZERO_MQ_ROLE_CLIENT":      2,
	}
)

func (x ZeroMQMuxHello_Role) Enum() *ZeroMQMuxHello_Role {
	p := new(ZeroMQMuxHello_Role)
	*p = x
	return p
}

func (x ZeroMQMuxHello_Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ZeroMQMuxHello_Role) Descriptor() protoreflect.EnumDescriptor {
	return file_transport_proto_enumTypes[0].Descriptor()
}

func (ZeroMQMuxHello_Role) Type() protoreflect.EnumType {
	return &file_transport_proto_enumTypes[0]
}

func (x ZeroMQMuxHello_Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ZeroMQMuxHello_Role.Descriptor instead.
func (ZeroMQMuxHello_Role) EnumDescriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{0, 0}
}

type ZeroMQMuxHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Role            ZeroMQMuxHello_Role    `protobuf:"varint,1,opt,name=role,proto3,enum=notifier.transport.v1.ZeroMQMuxHello_Role" json:"role,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ZeroMQMuxHello) Reset() {
	*x = ZeroMQMuxHello{}
	mi := &file_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZeroMQMuxHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZeroMQMuxHello) ProtoMessage() {}

func (x *ZeroMQMuxHello) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZeroMQMuxHello.ProtoReflect.Descriptor instead.
func (*ZeroMQMuxHello) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{0}
}

func (x *ZeroMQMuxHello) GetRole() ZeroMQMuxHello_Role {
	if x != nil {
		return x.Role
	}
	return ZeroMQMuxHello_ZERO_MQ_ROLE_UNSPECIFIED
}

func (x *ZeroMQMuxHello) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

var File_transport_proto protoreflect.FileDescriptor

const file_transport_proto_rawDesc = "" +
	"\n" +
	"\x0ftransport.proto\x12\x15notifier.transport.v1\"\xd4\x01\n" +
	"\x0eZeroMQMuxHello\x12>\n" +
	"\x04role\x18\x01 \x01(\x0e2*.notifier.transport.v1.ZeroMQMuxHello.RoleR\x04role\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\"W\n" +
	"\x04Role\x12\x1c\n" +
	"\x18ZERO_MQ_ROLE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ZERO_MQ_ROLE_CLUSTER\x10\x01\x12\x17\n" +
	"\x13ZERO_MQ_ROLE_CLIENT\x10\x02B/Z-github.com/tursom/turntf/internal/proto;protob\x06proto3"

var (
	file_transport_proto_rawDescOnce sync.Once
	file_transport_proto_rawDescData []byte
)

func file_transport_proto_rawDescGZIP() []byte {
	file_transport_proto_rawDescOnce.Do(func() {
		file_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_proto_rawDesc), len(file_transport_proto_rawDesc)))
	})
	return file_transport_proto_rawDescData
}

var file_transport_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_transport_proto_goTypes = []any{
	(ZeroMQMuxHello_Role)(0), // 0: notifier.transport.v1.ZeroMQMuxHello.Role
	(*ZeroMQMuxHello)(nil),   // 1: notifier.transport.v1.ZeroMQMuxHello
}
var file_transport_proto_depIdxs = []int32{
	0, // 0: notifier.transport.v1.ZeroMQMuxHello.role:type_name -> notifier.transport.v1.ZeroMQMuxHello.Role
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_transport_proto_init() }
func file_transport_proto_init() {
	if File_transport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_proto_rawDesc), len(file_transport_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transport_proto_goTypes,
		DependencyIndexes: file_transport_proto_depIdxs,
		EnumInfos:         file_transport_proto_enumTypes,
		MessageInfos:      file_transport_proto_msgTypes,
	}.Build()
	File_transport_proto = out.File
	file_transport_proto_goTypes = nil
	file_transport_proto_depIdxs = nil
}
